# Setup scoped CSS for local development
# This script copies the scoped CSS bundle generated by Blazor so the dev server can serve it.
#
# Usage:
#   .\setup-dev-scoped-css.ps1           # Setup for development
#   .\setup-dev-scoped-css.ps1 -Clean    # Remove the development CSS (for Release builds)

param(
    [switch]$Clean,
    [string]$BirkNextWebPath = "$PSScriptRoot/BirkNext.Web"
)

$sourceCss = Join-Path $BirkNextWebPath "obj/Debug/net8.0/scopedcss/bundle/BirkNext.Web.styles.css"
$destCss = Join-Path $BirkNextWebPath "wwwroot/BirkNext.Web.styles.css"

if ($Clean) {
    Write-Host "Removing development scoped CSS..." -ForegroundColor Yellow
    if (Test-Path $destCss) {
        Remove-Item $destCss -Force
        Write-Host "Removed: $destCss" -ForegroundColor Green
    } else {
        Write-Host "Nothing to clean - file not found." -ForegroundColor Gray
    }
} else {
    if (Test-Path $sourceCss) {
        Write-Host "Copying scoped CSS bundle to wwwroot for development..." -ForegroundColor Green
        Copy-Item $sourceCss $destCss -Force
        Write-Host "Done: $destCss" -ForegroundColor Green
        Write-Host ""
        Write-Host "CSS is ready for the dev server. CSS selectors will now render correctly in the browser." -ForegroundColor Gray
    } else {
        Write-Host "Error: Could not find scoped CSS bundle at $sourceCss" -ForegroundColor Red
        Write-Host "Please run: dotnet build BirkNext.Web -c Debug" -ForegroundColor Yellow
        exit 1
    }
}
