namespace BirkNext.Api.Models;

public enum QaReadinessStatus
{
    Ready,
    ReviewNeeded,
    HighRisk,
}

/// <summary>A single deduction from the deterministic quality score.</summary>
public sealed class QaScoreDeduction
{
    public string Category { get; init; } = string.Empty;
    public string Reason { get; init; } = string.Empty;
    public int Points { get; init; }
}

/// <summary>
/// Full AI QA audit report for a project. Computed on demand — not persisted.
///
/// Deterministic quality score (0–100) aggregated from:
///   - Coverage: TraceLinkService / SpecDriftDetectionService
///   - Spec Drift: SpecDriftDetectionService (which reuses ImpactAnalysisService)
///   - Code Traceability: CodeTraceabilityService
///
/// Optional AI layer (requires Anthropic:ApiKey in config):
///   - Executive summary, QA concerns, recommended actions generated by Claude.
///   - Only requested when includeAiSummary=true — graceful null fallback otherwise.
/// </summary>
public sealed class QaAuditReport
{
    // ── Overall ────────────────────────────────────────────────────────────────
    public int QualityScore { get; init; }
    public QaReadinessStatus ReadinessStatus { get; init; }

    // ── AI narrative (null when includeAiSummary=false or API key missing) ────
    public string? AiExecutiveSummary { get; init; }
    public IReadOnlyList<string> AiConcerns { get; init; } = [];
    public IReadOnlyList<string> AiRecommendedActions { get; init; } = [];

    // ── Dashboard card metrics ─────────────────────────────────────────────────
    public double CoveragePercent { get; init; }
    public int TotalRequirements { get; init; }
    public int RequirementsAtRisk { get; init; }
    /// <summary>Requirements with 0 linked tests (High Risk).</summary>
    public int HighRiskRequirements { get; init; }
    public int DriftFindingsCount { get; init; }
    public int HighRiskDriftFindings { get; init; }
    public int OrphanTestCount { get; init; }
    public int TotalCodeFiles { get; init; }
    public int UnlinkedCodeFiles { get; init; }

    // ── Detail sections ───────────────────────────────────────────────────────
    public IReadOnlyList<DriftFinding> DriftFindings { get; init; } = [];
    public IReadOnlyList<DriftRequirement> TopRisks { get; init; } = [];
    public IReadOnlyList<string> RecommendedActions { get; init; } = [];
    public IReadOnlyList<QaScoreDeduction> ScoreDeductions { get; init; } = [];
}
