using BirkNext.GeneratedDocumentation;
using BirkNext.Integrations;
using BirkNext.SourceArchitecture;
using BirkNext.Web.Components.GeneratedDocumentation;
using BirkNext.Web.Services;
using BirkNext.Web.Services.Explorers;
using Bunit;
using FluentAssertions;
using Microsoft.Extensions.DependencyInjection;
using Moq;

namespace BirkNext.Web.Tests.Components;

/// <summary>Generated Documentation Health (System Settings → Developer) and the Source Analysis summary: states, summary, filters, module
/// detail, drift evidence and the request the workspace sends. Generic fixtures only.</summary>
public sealed class GeneratedDocumentationHealthPanelTests : BunitContext
{
    private sealed class FakeApi(GeneratedDocumentationDiagnosticRun run) : IGeneratedDocumentationApiService
    {
        public GeneratedDocumentationDiagnosticRequest? LastRequest { get; private set; }
        public Task<GeneratedDocumentationDiagnosticRun?> RunAsync(GeneratedDocumentationDiagnosticRequest request, CancellationToken ct = default)
        {
            LastRequest = request;
            return Task.FromResult<GeneratedDocumentationDiagnosticRun?>(run);
        }
    }

    private static readonly Guid SnapshotId = Guid.Parse("11111111-2222-3333-4444-555555555555");

    private static CrossArtifactDriftCandidate Drift(string id, CrossArtifactDriftType type, string module, string key) => new()
    {
        Id = id, DriftType = type, ModuleId = module, Family = type == CrossArtifactDriftType.DocumentationDrift ? "HTTP routes" : "Specified routes", StructuredKey = key,
        DifferenceKind = DriftDifferenceKind.MissingOnRight, Confidence = ArchitectureEvidenceState.Confirmed, SourceSnapshotId = SnapshotId,
        LeftEvidence = [new("Generated documentation", "API contract · openapi.yaml", "shop/orders/generated-docs/a-very-long-path-segment-that-should-wrap/openapi.yaml", 0, "gendoc:x", "abcdef0123456789")],
        RightEvidence = [new("Source routes", "1 route(s) in scope shop/orders/", "shop/orders")],
        Explanation = $"Generated documentation states {key}; no matching route was found.", WhyReview = "Either side may be outdated.",
        GeneratedFreshness = GeneratedDocumentationFreshnessStatus.Current,
    };

    private static GeneratedDocumentationHealthResult Module(string name, GeneratedDocumentationHealthStatus status, GeneratedDocumentationFreshnessStatus freshness,
        bool generator = true, List<string>? source = null, List<string>? cross = null, List<string>? missing = null) => new()
    {
        Module = name, ModuleId = "module:" + name, RootPath = name, GeneratedDirectory = name + "/generated-docs", GeneratorDetected = generator,
        GeneratorSummary = generator ? "Agent workflow (doc-writer) — .claude/skills/doc-writer/SKILL.md" : "Likely generated / Unknown provenance",
        GeneratedDocsDetected = true, Freshness = freshness, FreshnessReason = "Reason for " + name, Status = status, StatusReason = "Status reason " + name,
        SourceDiscrepancies = source ?? [], CrossArtifactDrift = cross ?? [], MissingExpectedDocs = missing ?? [],
        Comparisons = [new("HTTP routes", source?.Count > 0 ? GeneratedComparisonState.PotentiallyDrifted : GeneratedComparisonState.Equivalent, "2 documented vs 1 source", source?.Count ?? 0)],
        Evidence = [new GeneratedDocumentationEvidence { EvidenceId = "gendoc:" + name, SafeRelativePath = name + "/generated-docs/openapi.yaml", DocumentKind = GeneratedDocumentKind.ApiContract,
            FreshnessStatus = freshness, Provenance = new GeneratedDocumentationProvenance { Label = generator ? "Generated by agent workflow (doc-writer)" : "Likely generated / Unknown provenance" } }],
    };

    private static GeneratedDocumentationDiagnosticRun ReadyRun() => new()
    {
        State = GeneratedDocumentationRunState.Ready, StateMessage = "ok", CompletedAt = DateTimeOffset.UtcNow, DurationMilliseconds = 12,
        Snapshot = new GeneratedDocumentationSnapshotBinding { SnapshotId = SnapshotId, ArchiveName = "shop.zip", Basis = "Newest Source Analysis snapshot", IsNewest = true, AnalyzedAt = DateTimeOffset.UtcNow },
        Summary = new GeneratedDocumentationSummary { ModulesWithGeneratedDocs = 3, ModulesWithGeneratorDetected = 2, Fresh = 1, PotentiallyStale = 1, FreshnessUnknown = 1, SourceDocumentationDiscrepancies = 1, CrossArtifactDriftCandidates = 1 },
        Modules =
        [
            Module("orders", GeneratedDocumentationHealthStatus.Warning, GeneratedDocumentationFreshnessStatus.Stale, source: ["drift:1"], cross: ["drift:2"]),
            Module("billing", GeneratedDocumentationHealthStatus.Pass, GeneratedDocumentationFreshnessStatus.Current),
            Module("catalog", GeneratedDocumentationHealthStatus.Partial, GeneratedDocumentationFreshnessStatus.Unknown, generator: false),
        ],
        Generators = [new GeneratorWorkflowEvidence { Id = "workflow:x", Type = GeneratorType.AgentWorkflow, GeneratorName = "doc-writer", Path = ".claude/skills/doc-writer/SKILL.md", Role = "Agent skill definition", Basis = "Declares generated-docs/ as an output" }],
        Drift = [Drift("drift:1", CrossArtifactDriftType.DocumentationDrift, "module:orders", "GET /invoices"), Drift("drift:2", CrossArtifactDriftType.SpecificationDrift, "module:orders", "GET /refunds")],
        Authored = new AuthoredComparisonState(true, "Compared.", ["Specification · spec.md"]),
        Limitations = [GeneratedDocumentationText.NotSynchronized],
    };

    private IRenderedComponent<GeneratedDocumentationHealthPanel> RenderWith(GeneratedDocumentationDiagnosticRun run, out FakeApi api)
    {
        var fake = new FakeApi(run);
        api = fake;
        return Render<GeneratedDocumentationHealthPanel>(p => p.Add(x => x.Api, fake));
    }

    [Fact]
    public void Shows_the_description_and_runs_on_request_only()
    {
        var cut = RenderWith(ReadyRun(), out var api);
        cut.Find("[data-testid=gdh-description]").TextContent.Should().Be(GeneratedDocumentationText.Description);
        cut.Find("[data-testid=gdh-not-run]");
        api.LastRequest.Should().BeNull();
        cut.Find("[data-testid=gdh-run]").Click();
        cut.WaitForAssertion(() => cut.Find("[data-testid=gdh-summary]"));
        api.LastRequest.Should().NotBeNull();
    }

    [Fact]
    public void Summary_has_counts_and_no_score()
    {
        var cut = RenderWith(ReadyRun(), out _);
        cut.Find("[data-testid=gdh-run]").Click();
        cut.WaitForAssertion(() => cut.FindAll("[data-testid=gdh-card]").Should().HaveCount(8));
        cut.Find("[data-metric=stale] dd").TextContent.Should().Be("1");
        cut.Find("[data-metric=drift] dd").TextContent.Should().Be("1");
        cut.Markup.Should().NotContain("%").And.NotContain("Score");
        cut.Find("[data-testid=gdh-authored-state]").TextContent.Should().Contain("compared");
    }

    [Fact]
    public void Filters_select_modules_by_fact_and_mark_the_active_filter_without_colour_alone()
    {
        var cut = RenderWith(ReadyRun(), out _);
        cut.Find("[data-testid=gdh-run]").Click();
        cut.WaitForAssertion(() => cut.FindAll("[data-testid=gdh-module]").Should().HaveCount(3));
        cut.Find("[data-filter=PotentiallyStale]").Click();
        cut.FindAll("[data-testid=gdh-module]").Select(m => m.GetAttribute("data-module")).Should().Equal("orders");
        cut.Find("[data-filter=PotentiallyStale]").GetAttribute("aria-pressed").Should().Be("true");
        cut.Find("[data-filter=UnknownFreshness]").Click();
        cut.FindAll("[data-testid=gdh-module]").Select(m => m.GetAttribute("data-module")).Should().Equal("catalog");
        cut.Find("[data-filter=CrossArtifactDrift]").Click();
        cut.FindAll("[data-testid=gdh-module]").Select(m => m.GetAttribute("data-module")).Should().Equal("orders");
        cut.Find("[data-filter=MissingExpectedDocs]").Click();
        cut.Find("[data-testid=gdh-filter-empty]");
        // Status is text, not only colour.
        cut.Find("[data-filter=All]").Click();
        cut.FindAll("[data-testid=gdh-module-status]").Select(s => s.TextContent).Should().Equal("Needs review", "Pass", "Partial");
        cut.FindAll("[data-testid=gdh-module-freshness]")[0].TextContent.Should().Contain("Potentially stale");
    }

    [Fact]
    public void Module_details_and_drift_evidence_expand_with_both_sides_and_why_review_is_needed()
    {
        var cut = RenderWith(ReadyRun(), out _);
        cut.Find("[data-testid=gdh-run]").Click();
        cut.WaitForAssertion(() => cut.FindAll("[data-testid=gdh-module-toggle]").Should().HaveCount(3));
        var toggle = cut.FindAll("[data-testid=gdh-module-toggle]")[0];
        toggle.GetAttribute("aria-expanded").Should().Be("false");
        toggle.Click();
        cut.FindAll("[data-testid=gdh-module-toggle]")[0].GetAttribute("aria-expanded").Should().Be("true");
        cut.Find("[data-testid=gdh-module-details]");
        cut.FindAll("[data-testid=gdh-drift]").Should().HaveCount(2);
        cut.Find("[data-testid=gdh-drift]").TextContent.Should().Contain(GeneratedDocumentationText.ReviewStatus);
        cut.FindAll("[data-testid=gdh-drift-toggle]")[0].Click();
        var evidence = cut.Find("[data-testid=gdh-evidence]");
        evidence.TextContent.Should().Contain("Left").And.Contain("Right").And.Contain("Why review is needed").And.Contain(SnapshotId.ToString());
        evidence.TextContent.Should().Contain("a-very-long-path-segment-that-should-wrap");
    }

    [Fact]
    public void Neutral_empty_state_and_no_generator_state()
    {
        var empty = ReadyRun() with { State = GeneratedDocumentationRunState.NoGeneratedDocumentation, StateMessage = GeneratedDocumentationText.EmptyState, Modules = [], Drift = [] };
        var cut = RenderWith(empty, out _);
        cut.Find("[data-testid=gdh-run]").Click();
        cut.WaitForAssertion(() => cut.Find("[data-testid=gdh-state]").TextContent.Should().Contain(GeneratedDocumentationText.EmptyState));
        cut.Markup.Should().NotContain("sd-pill-attention");

        var noGenerator = RenderWith(ReadyRun(), out _);
        noGenerator.Find("[data-testid=gdh-run]").Click();
        noGenerator.WaitForAssertion(() => noGenerator.FindAll("[data-testid=gdh-module]").Should().HaveCount(3));
        noGenerator.FindAll("[data-testid=gdh-module]")[2].TextContent.Should().Contain(GeneratedDocumentationText.NoGenerator);
    }

    [Fact]
    public async Task The_request_carries_the_imported_project_and_its_selected_artifacts_only()
    {
        var artifact = new ExplorerArtifact("a1", WorkspaceArtifactType.Specification, "spec.md", "spec.md", "shop/orders/specs/001-orders/spec.md",
            ExplorerArtifactSource.Workspace, "ProjectImport", 1, 1, "Draft", ExplorerArtifactCurrentness.Current, null);
        var context = new Mock<IArtifactExplorerContext>();
        context.SetupGet(c => c.CurrentScope).Returns(ProjectImportScope.For("import-123"));
        context.Setup(c => c.GetStateAsync(It.IsAny<WorkspaceArtifactType>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync((WorkspaceArtifactType role, CancellationToken _) => role == WorkspaceArtifactType.Specification
                ? new ArtifactExplorerState(role, ExplorerArtifactStatus.Loaded, null, "Shop", [artifact], artifact, ExplorerSelectionReason.Explicit, "# Spec\n\nGET /orders\n")
                : new ArtifactExplorerState(role, ExplorerArtifactStatus.Empty, null, "Shop", []));
        var inputs = await TraceabilityInputs.ResolveAsync(context.Object);
        var request = GeneratedDocumentationApiService.Request(inputs);
        request.ProjectImportId.Should().Be("import-123");
        request.AuthoredArtifacts.Should().ContainSingle();
        request.AuthoredArtifacts[0].Role.Should().Be("Specification");
        request.AuthoredArtifacts[0].SourcePath.Should().Be("shop/orders/specs/001-orders/spec.md");
        GeneratedDocumentationApiService.Request(null).AuthoredArtifacts.Should().BeEmpty();
    }

    [Fact]
    public void Source_Analysis_summary_links_to_the_diagnostic_and_handles_older_snapshots()
    {
        var older = Render<GeneratedDocumentationSourceSummary>(p => p.Add(x => x.Snapshot, new IqrSourceSnapshot()));
        older.Find("[data-testid=sa-generated-docs-missing]");
        older.Find("[data-testid=sa-generated-docs-link]").GetAttribute("href").Should().Be("admin/system-settings?section=generated-docs-health");

        var none = Render<GeneratedDocumentationSourceSummary>(p => p.Add(x => x.Snapshot, new IqrSourceSnapshot { GeneratedDocumentation = new GeneratedDocumentationSnapshot() }));
        none.Find("[data-testid=sa-generated-docs-empty]").TextContent.Should().Be(GeneratedDocumentationText.EmptyState);

        var stale = new GeneratedDocumentationSnapshot
        {
            Documents = [new GeneratedDocumentationEvidence { EvidenceId = "d", Origin = DocumentationOrigin.Generated }],
            Modules = [new GeneratedDocumentationModule { ModuleId = "m", Freshness = GeneratedDocumentationFreshnessStatus.Stale, GeneratorIds = ["w"] }],
        };
        var some = Render<GeneratedDocumentationSourceSummary>(p => p.Add(x => x.Snapshot, new IqrSourceSnapshot { GeneratedDocumentation = stale }));
        some.Find("[data-testid=sa-generated-docs-status]").TextContent.Should().Be("Needs review");
    }

    [Fact]
    public void Presentation_filters_and_tones_are_fact_based()
    {
        var run = ReadyRun();
        GeneratedDocumentationPresentation.Count(run, GeneratedDocumentationFilter.All).Should().Be(3);
        GeneratedDocumentationPresentation.Count(run, GeneratedDocumentationFilter.Fresh).Should().Be(1);
        GeneratedDocumentationPresentation.Count(run, GeneratedDocumentationFilter.SourceDiscrepancies).Should().Be(1);
        GeneratedDocumentationPresentation.Tone(GeneratedDocumentationHealthStatus.Warning).Should().Be("partial");
        GeneratedDocumentationPresentation.Tone(GeneratedDocumentationHealthStatus.Fail).Should().Be("attention");
        GeneratedDocumentationPresentation.Tone(GeneratedDocumentationFreshnessStatus.Stale).Should().Be("partial", "staleness needs review; it is never red");
        GeneratedDocumentationPresentation.DriftFor(run, run.Modules[0]).Select(d => d.Id).Should().Equal("drift:1", "drift:2");
    }
}
