using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using BirkNext.GeneratedDocumentation;
using BirkNext.Integrations;
using BirkNext.Api.Services.Integrations.ApplicationMessaging;
using BirkNext.SourceArchitecture;

namespace BirkNext.Api.Services.SourceAnalysis.GeneratedDocumentation;

/// <summary>
/// Directory conventions for generated documentation. A convention is a strong but not required signal: a workflow that declares another
/// output directory is honoured the same way. Configurable per analysis; the defaults name no project.
/// </summary>
public sealed record GeneratedDocumentationOptions
{
    /// <summary>Directory names that hold generated documentation by convention (matched on one path segment, case-insensitive).</summary>
    public IReadOnlyList<string> ConventionDirectories { get; init; } =
        ["autodoc", "autodocs", "generated-docs", "generated-documentation", "docs-generated", "gen-docs", "autogen-docs"];
    /// <summary>Multi-segment directory suffixes that hold generated documentation by convention.</summary>
    public IReadOnlyList<string> ConventionPaths { get; init; } =
        ["docs/generated", "doc/generated", "docs/autogen", "documentation/generated", "architecture/generated", "build/docs", "generated/docs", "docs/api/generated"];
    /// <summary>Directory names that are containers, not module roots: an output under docs/ or build/ documents the folder above it.</summary>
    public IReadOnlyList<string> ContainerDirectories { get; init; } = ["docs", "doc", "documentation", "build", "generated", "out", "site"];

    public static GeneratedDocumentationOptions Default { get; } = new();
}

/// <summary>A file the detector classified as a generated document, with its content for this analysis only (never stored).</summary>
internal sealed record DetectedDocument(string Path, string Content, string Directory, string ModuleRoot, GeneratedDocumentKind Kind, string KindBasis,
    DocumentationOrigin Origin, string OriginBasis, List<string> WorkflowIds, GeneratedDocumentationProvenance Provenance);

internal sealed record DetectedDirectory(string Path, string ModuleRoot, bool Convention, List<string> DeclaringWorkflowIds, List<string> ReferencingWorkflowIds, List<string> DeclaredFiles);

internal sealed record DetectionResult(List<GeneratorWorkflowEvidence> Generators, List<DetectedDirectory> Directories, List<DetectedDocument> Documents,
    int AuthoredDocuments, int UnclassifiedDocuments, List<string> Limitations);

/// <summary>
/// Generated-documentation detection over one snapshot's files: workflow/generator files (agent skills and hooks, documentation tool
/// configuration, build targets, documentation scripts), generated-documentation directories (conventions and workflow declarations), the
/// origin of each document (Generated / Authored / Unknown) and its kind. Provenance is only what files show: an agent workflow is named only
/// when its definition names itself, and a folder no workflow declares is "Likely generated / Unknown provenance".
/// </summary>
internal static class GeneratedDocumentationDetector
{
    private static readonly Regex FrontMatterName = new(@"\A---\s*\n(?:.*\n)*?name:\s*[""']?([A-Za-z0-9][\w .:-]{0,80}?)[""']?\s*\n(?:.*\n)*?---", RegexOptions.Compiled);
    private static readonly Regex OutputVerb = new(@"(?i)\b(outputs?|writes?|written|goes\s+to|write\s+to|generates?|produces?|emits?)\b", RegexOptions.Compiled);
    private static readonly Regex GeneratedMarker = new(@"(?i)(<!--\s*(auto-?)?generated|\bauto-?generated\b|\bdo not edit\b|\bthis (file|document) (is|was) (auto-?)?generated\b|^\s*#?\s*generated by\b)", RegexOptions.Compiled | RegexOptions.Multiline);
    /// <summary>Authored Spec-Kit artifacts: everything in a feature folder (spec, plan, tasks, data model, research, contracts, checklists) and the
    /// project memory (.specify/, constitution). A workflow that writes them does not make them generated documentation.</summary>
    private static readonly Regex SpecKitAuthored = new(@"(?i)(^|/)(\.specify/|specs/[^/]+/)|(^|/)[^/]*constitution\.md$", RegexOptions.Compiled);
    /// <summary>Agent context/instruction files (CLAUDE.md, AGENTS.md …) configure a workflow; they are not documentation of the code even when a script writes them.</summary>
    private static readonly Regex AgentContextFile = new(@"(?i)(^|/)(CLAUDE|AGENTS|GEMINI|COPILOT|CURSOR)(\.local)?\.md$|(^|/)copilot-instructions\.md$|(^|/)\.cursorrules$", RegexOptions.Compiled);
    private static readonly HashSet<string> AgentFolders = new(StringComparer.OrdinalIgnoreCase) { ".claude", ".cursor", ".windsurf", ".continue", ".aider" };
    private static readonly Regex DocToolConfig = new(@"(?i)(^|/)(mkdocs\.ya?ml|docfx\.json|typedoc\.json|Doxyfile|\.redocly\.ya?ml|redocly\.ya?ml|antora\.ya?ml|jsdoc\.json|\.jsdoc\.json|book\.toml)$", RegexOptions.Compiled);

    public static DetectionResult Detect(IReadOnlyList<SourceFile> files, IReadOnlyList<string> allPaths, GeneratedDocumentationOptions? options = null)
    {
        options ??= GeneratedDocumentationOptions.Default;
        var byPath = files.GroupBy(f => f.Path, StringComparer.Ordinal).ToDictionary(g => g.Key, g => g.First(), StringComparer.Ordinal);
        var limitations = new List<string>();

        // ── 1. Directories that hold documentation files (the only directories a workflow can declare as a documentation output) ──
        var docDirectories = allPaths.Where(p => IsDocumentFile(p) && !SpecKitAuthored.IsMatch(p) && !p.Split('/').Any(AgentFolders.Contains))
            .Select(DirectoryOf).Where(d => d.Length > 0).ToHashSet(StringComparer.Ordinal);
        bool IsConventionDirectory(string dir) =>
            options.ConventionDirectories.Any(c => Leaf(dir).Equals(c, StringComparison.OrdinalIgnoreCase))
            || options.ConventionPaths.Any(c => dir.Equals(c, StringComparison.OrdinalIgnoreCase) || dir.EndsWith("/" + c, StringComparison.OrdinalIgnoreCase));

        // ── 2. Workflow / generator files ──
        var generators = new List<GeneratorWorkflowEvidence>();
        foreach (var file in files.OrderBy(f => f.Path, StringComparer.Ordinal))
        {
            var (type, role) = WorkflowRole(file.Path, file.Content);
            if (type is null) continue;
            var declared = new List<string>();
            var referencedDirs = new List<string>();
            var declaredFiles = new List<string>();
            foreach (var (token, isLeaf) in DirectoryTokens(file.Content, docDirectories, options))
            {
                if (DeclaresOutput(file.Content, token, role)) declared.Add(token); else referencedDirs.Add(token);
            }
            foreach (var token in declared)
            {
                var leafToken = token.TrimEnd('/');
                foreach (Match m in Regex.Matches(file.Content, @"(?<![\w-])" + Regex.Escape(leafToken) + @"/([A-Za-z0-9][\w.-]*\.[A-Za-z0-9]{1,8})\b"))
                    declaredFiles.Add(m.Groups[1].Value);
            }
            var references = Regex.Matches(file.Content, @"(?<![\w-])((?:\.claude|\.cursor|\.github|scripts?|tools?)/[\w./-]+\.[A-Za-z0-9]{1,6})").Select(m => m.Groups[1].Value)
                .Where(p => allPaths.Contains(p, StringComparer.Ordinal) && p != file.Path).Distinct(StringComparer.Ordinal).ToList();
            if (declared.Count == 0 && referencedDirs.Count == 0 && references.Count == 0 && type != GeneratorType.DocumentationTool) continue;
            generators.Add(new GeneratorWorkflowEvidence
            {
                Id = "workflow:" + Safe(file.Path), Type = type.Value, Path = Safe(file.Path), Role = role,
                GeneratorName = role == "Agent skill definition" || role == "Agent command definition" ? FrontMatterName.Match(file.Content.Replace("\r\n", "\n")) is { Success: true } n ? Safe(n.Groups[1].Value.Trim()) : null : null,
                DeclaredOutputDirectories = declared.Distinct(StringComparer.OrdinalIgnoreCase).ToList(),
                DeclaredOutputFiles = declaredFiles.Distinct(StringComparer.OrdinalIgnoreCase).Order(StringComparer.OrdinalIgnoreCase).ToList(),
                References = references.Concat(referencedDirs.Select(d => d)).Distinct(StringComparer.Ordinal).Select(Safe).ToList(),
                Basis = declared.Count > 0 ? $"Declares {string.Join(", ", declared.Distinct(StringComparer.OrdinalIgnoreCase))} as an output" : referencedDirs.Count > 0 ? $"References {string.Join(", ", referencedDirs.Distinct(StringComparer.OrdinalIgnoreCase))}" : "References other workflow files",
                ContentFingerprint = Fingerprint(file.Content),
            });
        }
        // A hook registration (agent settings) links the hook scripts it registers; a script linked this way inherits nothing but the link.
        var workflowsByPath = generators.ToDictionary(g => g.Path, StringComparer.Ordinal);

        // ── 3. Generated-documentation directories ──
        var directories = new Dictionary<string, (bool Convention, HashSet<string> Declaring, HashSet<string> Referencing, HashSet<string> Files)>(StringComparer.Ordinal);
        void AddDirectory(string dir, bool convention, GeneratorWorkflowEvidence? declaring, GeneratorWorkflowEvidence? referencing)
        {
            if (!directories.TryGetValue(dir, out var entry)) directories[dir] = entry = (convention, new(StringComparer.Ordinal), new(StringComparer.Ordinal), new(StringComparer.OrdinalIgnoreCase));
            if (convention && !entry.Convention) directories[dir] = entry = (true, entry.Declaring, entry.Referencing, entry.Files);
            if (declaring is not null) { entry.Declaring.Add(declaring.Id); foreach (var f in declaring.DeclaredOutputFiles) entry.Files.Add(f); }
            if (referencing is not null) entry.Referencing.Add(referencing.Id);
        }
        foreach (var dir in docDirectories.Where(IsConventionDirectory)) AddDirectory(dir, true, null, null);
        foreach (var g in generators)
        {
            foreach (var token in g.DeclaredOutputDirectories) foreach (var dir in Resolve(token, docDirectories, options)) AddDirectory(dir, IsConventionDirectory(dir), g, null);
            foreach (var token in g.References.Where(r => r.EndsWith('/'))) foreach (var dir in Resolve(token, docDirectories, options).Where(directories.ContainsKey)) AddDirectory(dir, IsConventionDirectory(dir), null, g);
        }
        // Nested folders of a generated directory belong to it (e.g. autodoc/diagrams).
        var roots = directories.Keys.Where(d => !directories.Keys.Any(o => o != d && d.StartsWith(o + "/", StringComparison.Ordinal))).ToList();
        foreach (var nested in directories.Keys.Except(roots).ToList()) directories.Remove(nested);

        // ── 4. Documents ──
        var documents = new List<DetectedDocument>();
        var detectedDirectories = new List<DetectedDirectory>();
        foreach (var (dir, entry) in directories.OrderBy(d => d.Key, StringComparer.Ordinal))
        {
            var moduleRoot = ModuleRoot(dir, options);
            detectedDirectories.Add(new DetectedDirectory(dir, moduleRoot, entry.Convention, [.. entry.Declaring.Order(StringComparer.Ordinal)], [.. entry.Referencing.Order(StringComparer.Ordinal)], [.. entry.Files.Order(StringComparer.OrdinalIgnoreCase)]));
            var declaring = entry.Declaring.Select(id => generators.First(g => g.Id == id)).ToList();
            var referencing = entry.Referencing.Select(id => generators.First(g => g.Id == id)).ToList();
            // Hook registrations whose registered script references this directory support provenance as configuration.
            var configs = generators.Where(g => g.Role == "Agent hook registration" && g.References.Any(r => workflowsByPath.TryGetValue(r, out var script)
                && (entry.Declaring.Contains(script.Id) || entry.Referencing.Contains(script.Id)))).ToList();
            foreach (var path in allPaths.Where(p => p.StartsWith(dir + "/", StringComparison.Ordinal)).Order(StringComparer.Ordinal))
            {
                if (!byPath.TryGetValue(path, out var file) || !IsDocumentFile(path)) continue;
                if (SpecKitAuthored.IsMatch(path)) continue;
                var (kind, kindBasis) = Classify(path, file.Content);
                var name = System.IO.Path.GetFileName(path);
                var declaredOutput = entry.Files.Count == 0 || entry.Files.Contains(name);
                var origin = declaredOutput ? DocumentationOrigin.Generated : DocumentationOrigin.Unknown;
                var originBasis = !declaredOutput
                    ? $"In generated folder {Safe(dir)}/ but not a declared output of {string.Join(", ", declaring.Select(d => d.GeneratorName ?? d.Path))} — origin not established"
                    : declaring.Count > 0 ? $"Declared output folder of {string.Join(", ", declaring.Select(d => d.Path))}"
                    : entry.Convention ? $"Generated-documentation folder convention ({Leaf(dir)}/)" : "Referenced generated folder";
                var provenance = Provenance(dir, entry.Convention, declaring, referencing, configs);
                documents.Add(new DetectedDocument(path, file.Content, dir, moduleRoot, kind, kindBasis, origin, originBasis,
                    declaring.Concat(referencing).Concat(configs).Select(g => g.Id).Distinct(StringComparer.Ordinal).ToList(), provenance));
            }
        }
        // A declared or conventional folder whose files are all authored (e.g. a specification folder a workflow writes) is not a generated folder.
        detectedDirectories.RemoveAll(d => documents.All(doc => doc.Directory != d.Path));
        // Single files outside a generated folder with an explicit generated marker in their header (never Spec-Kit authored artifacts).
        foreach (var file in files.Where(f => IsDocumentFile(f.Path) && !documents.Any(d => d.Path == f.Path) && !SpecKitAuthored.IsMatch(f.Path)
            && !f.Path.Split('/').Any(AgentFolders.Contains) && !AgentContextFile.IsMatch(f.Path) && GeneratedMarker.IsMatch(Head(f.Content, 6))).OrderBy(f => f.Path, StringComparer.Ordinal))
        {
            var dir = DirectoryOf(file.Path);
            var (kind, kindBasis) = Classify(file.Path, file.Content);
            // A single generated file documents the folder it sits in (or the folder above a container such as docs/).
            var fileRoot = dir;
            while (fileRoot.Length > 0 && options.ContainerDirectories.Contains(Leaf(fileRoot), StringComparer.OrdinalIgnoreCase)) fileRoot = DirectoryOf(fileRoot);
            documents.Add(new DetectedDocument(file.Path, file.Content, dir, fileRoot, kind, kindBasis,
                DocumentationOrigin.Generated, "Generated marker in the document header", [],
                new GeneratedDocumentationProvenance { GeneratorType = GeneratorType.Unknown, Confidence = ArchitectureEvidenceState.Inferred, Label = "Likely generated / Unknown provenance",
                    DetectedFrom = [$"Generated marker in {Safe(file.Path)}"] }));
        }
        var authored = allPaths.Count(p => IsDocumentFile(p) && SpecKitAuthored.IsMatch(p));
        var unclassified = allPaths.Count(p => p.EndsWith(".md", StringComparison.OrdinalIgnoreCase) && !SpecKitAuthored.IsMatch(p) && documents.All(d => d.Path != p)
            && !p.Split('/').Any(AgentFolders.Contains) && !AgentContextFile.IsMatch(p));
        if (files.Count == 0) limitations.Add("No documentation files were available to this analysis.");
        return new DetectionResult(generators, detectedDirectories, documents, authored, unclassified, limitations);
    }

    private static GeneratedDocumentationProvenance Provenance(string dir, bool convention, List<GeneratorWorkflowEvidence> declaring, List<GeneratorWorkflowEvidence> referencing, List<GeneratorWorkflowEvidence> configs)
    {
        var detectedFrom = new List<string>();
        detectedFrom.AddRange(declaring.Select(d => $"{d.Role} {d.Path} declares {Safe(dir)}/ as an output"));
        detectedFrom.AddRange(configs.Select(c => $"{c.Role} {c.Path} registers a workflow that references {Safe(dir)}/"));
        detectedFrom.AddRange(referencing.Select(r => $"{r.Role} {r.Path} references {Safe(dir)}/ (not declared as its output)"));
        if (convention) detectedFrom.Add($"Directory convention: {Leaf(dir)}/");
        if (declaring.Count == 0)
            return new GeneratedDocumentationProvenance
            {
                GeneratorType = GeneratorType.Unknown, Confidence = ArchitectureEvidenceState.Inferred, DetectedFrom = detectedFrom,
                Label = "Likely generated / Unknown provenance",
            };
        var type = declaring.Select(d => d.Type).OrderBy(t => t switch { GeneratorType.AgentWorkflow => 0, GeneratorType.DocumentationTool => 1, GeneratorType.BuildGenerator => 2, GeneratorType.Script => 3, _ => 4 }).First();
        var names = declaring.Where(d => d.GeneratorName is not null).Select(d => d.GeneratorName!).Distinct(StringComparer.Ordinal).ToList();
        return new GeneratedDocumentationProvenance
        {
            GeneratorType = type,
            GeneratorName = names.Count > 0 ? string.Join(", ", names) : null,
            GeneratorWorkflowPath = declaring[0].Path,
            GeneratorConfigPath = configs.FirstOrDefault()?.Path ?? declaring.FirstOrDefault(d => d.Type == GeneratorType.DocumentationTool)?.Path,
            DetectedFrom = detectedFrom,
            Confidence = names.Count > 0 ? ArchitectureEvidenceState.Confirmed : ArchitectureEvidenceState.StronglySupported,
            Label = $"Generated by {GeneratedDocumentationText.Label(type).ToLowerInvariant()}{(names.Count > 0 ? $" ({string.Join(", ", names)})" : "")}",
        };
    }

    /// <summary>Whether a workflow file declares <paramref name="token"/> as an output: an output verb before the token on the same line
    /// (within 60 characters), or a heading that names outputs. A mention alone is a reference (the workflow may read that folder).</summary>
    private static bool DeclaresOutput(string content, string token, string role)
    {
        if (role is "Agent hook script" or "Agent hook registration" or "Agent workflow documentation") return false;
        var pattern = new Regex(@"(?<![\w-])" + Regex.Escape(token.TrimEnd('/')) + @"/", RegexOptions.IgnoreCase);
        foreach (var line in content.Replace("\r\n", "\n").Split('\n'))
        {
            foreach (Match m in pattern.Matches(line))
            {
                var before = line[..m.Index];
                var window = before.Length > 60 ? before[^60..] : before;
                if (OutputVerb.IsMatch(window)) return true;
                if (line.TrimStart().StartsWith('#') && Regex.IsMatch(line, @"(?i)\boutput")) return true;
            }
        }
        return false;
    }

    /// <summary>Directory tokens a workflow file names: explicit documentation directories of the archive ("docs/architecture/") and generated
    /// directory conventions ("autodoc/"). Placeholders like "&lt;Module&gt;/autodoc/" resolve through the convention leaf.</summary>
    private static IEnumerable<(string Token, bool Leaf)> DirectoryTokens(string content, HashSet<string> docDirectories, GeneratedDocumentationOptions options)
    {
        var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var convention in options.ConventionDirectories)
            if (Regex.IsMatch(content, @"(?<![\w-])" + Regex.Escape(convention) + @"/", RegexOptions.IgnoreCase) && seen.Add(convention + "/")) yield return (convention + "/", true);
        foreach (Match m in Regex.Matches(content, @"(?<![\w.<>/-])((?:[A-Za-z0-9_.-]+/)+)(?=[\s`'"")\],|*]|$)", RegexOptions.Multiline))
        {
            var dir = m.Groups[1].Value.TrimEnd('/');
            if (dir.Contains("..") || !docDirectories.Contains(dir)) continue;
            if (seen.Add(dir + "/")) yield return (dir + "/", false);
        }
    }

    private static IEnumerable<string> Resolve(string token, HashSet<string> docDirectories, GeneratedDocumentationOptions options)
    {
        var t = token.TrimEnd('/');
        var leaf = !t.Contains('/') && options.ConventionDirectories.Contains(t, StringComparer.OrdinalIgnoreCase);
        // A convention token ("autodoc/") names every folder with that name; an explicit path names exactly that repository-relative folder.
        return leaf ? docDirectories.Where(d => Leaf(d).Equals(t, StringComparison.OrdinalIgnoreCase)) : docDirectories.Where(d => d.Equals(t, StringComparison.Ordinal));
    }

    private static (GeneratorType? Type, string Role) WorkflowRole(string path, string content)
    {
        var segments = path.Split('/');
        var name = System.IO.Path.GetFileName(path);
        if (segments.Any(AgentFolders.Contains) || segments.Contains("prompts") && segments.Contains(".github", StringComparer.OrdinalIgnoreCase))
        {
            if (name.Equals("SKILL.md", StringComparison.OrdinalIgnoreCase) || segments.Contains("skills", StringComparer.OrdinalIgnoreCase)) return (GeneratorType.AgentWorkflow, "Agent skill definition");
            if (segments.Contains("commands", StringComparer.OrdinalIgnoreCase) || segments.Contains("prompts", StringComparer.OrdinalIgnoreCase) || segments.Contains("rules", StringComparer.OrdinalIgnoreCase))
                return (GeneratorType.AgentWorkflow, "Agent command definition");
            if (segments.Contains("hooks", StringComparer.OrdinalIgnoreCase)) return (GeneratorType.AgentWorkflow, "Agent hook script");
            if (name.StartsWith("settings", StringComparison.OrdinalIgnoreCase) && name.EndsWith(".json", StringComparison.OrdinalIgnoreCase))
                return Regex.IsMatch(content, @"""hooks""\s*:") ? (GeneratorType.AgentWorkflow, "Agent hook registration") : (null, "");
            if (name.EndsWith(".md", StringComparison.OrdinalIgnoreCase)) return (GeneratorType.AgentWorkflow, "Agent workflow documentation");
            return (null, "");
        }
        if (DocToolConfig.IsMatch(path)) return (GeneratorType.DocumentationTool, "Documentation tool configuration");
        if (name.Equals("package.json", StringComparison.OrdinalIgnoreCase) && Regex.IsMatch(content, @"""scripts""\s*:\s*\{[^}]*""[\w:-]*docs?[\w:-]*""\s*:", RegexOptions.IgnoreCase))
            return (GeneratorType.BuildGenerator, "Build target");
        if (name.EndsWith(".csproj", StringComparison.OrdinalIgnoreCase) && Regex.IsMatch(content, @"(?i)(swagger\s+tofile|OpenApiGenerateDocuments|<Target[^>]*Name=""[^""]*Doc)"))
            return (GeneratorType.BuildGenerator, "Build target");
        if (Integrations.SourceEvidence.IqrSourceArchiveReader.IsDocumentationWorkflowCandidate(path) && !name.EndsWith(".md", StringComparison.OrdinalIgnoreCase))
            return (GeneratorType.Script, "Script");
        return (null, "");
    }

    /// <summary>Kind from path, format AND content. The file name is one signal; content markers (OpenAPI root keys, SDL, mermaid diagram
    /// types, changelog version headings, entity/route/topic tables) decide when the name is generic.</summary>
    public static (GeneratedDocumentKind Kind, string Basis) Classify(string path, string content)
    {
        var name = System.IO.Path.GetFileNameWithoutExtension(path).ToLowerInvariant();
        var ext = System.IO.Path.GetExtension(path).ToLowerInvariant();
        var head = Head(content, 80);
        if (ext is ".yaml" or ".yml" or ".json")
        {
            var json = ext == ".json";
            if (Regex.IsMatch(head, json ? @"""(openapi|swagger)""\s*:" : @"(?m)^\s*[""']?(openapi|swagger)[""']?\s*:")) return (GeneratedDocumentKind.ApiContract, "OpenAPI/Swagger root key");
            if (Regex.IsMatch(head, json ? @"""asyncapi""\s*:" : @"(?m)^\s*[""']?asyncapi[""']?\s*:")) return (GeneratedDocumentKind.Messaging, "AsyncAPI root key");
            return (GeneratedDocumentKind.OtherGeneratedDocumentation, $"{ext} document without a recognised contract root");
        }
        if (ext is ".graphql" or ".graphqls" or ".gql") return (GeneratedDocumentKind.GraphQlSchema, "GraphQL SDL file");
        if (ext is ".xsd" or ".proto") return (GeneratedDocumentKind.ApiContract, $"{ext} schema file");
        var structure = new DocumentStructure(content);
        bool NameHas(string pattern) => Regex.IsMatch(name, pattern);
        bool Mermaid(string type) => structure.Fences.Any(f => f.Language.StartsWith("mermaid", StringComparison.Ordinal) && Regex.IsMatch(f.Body, @"^\s*" + type, RegexOptions.IgnoreCase | RegexOptions.Multiline));
        if (NameHas(@"^(changelog|changes|history|release[-_ ]?notes)") || Regex.Matches(content, @"(?m)^#{1,3}\s*\[?v?\d+\.\d+(\.\d+)?\]?\s*[—–-]?\s*\d{4}-\d{2}-\d{2}").Count >= 2)
            return (GeneratedDocumentKind.Changelog, NameHas("^(changelog|changes|history|release)") ? "Changelog file name" : "Dated version headings");
        if (NameHas(@"route|sitemap|pages")) return (GeneratedDocumentKind.Routes, "Routes file name");
        if (NameHas(@"data[-_ ]?model|datamodel|entities|erd|database|schema")) return (GeneratedDocumentKind.DataModel, "Data-model file name");
        if (NameHas(@"message|bus|event|topic|queue|messaging|routing|hub")) return (GeneratedDocumentKind.Messaging, "Messaging file name");
        if (NameHas(@"data[-_ ]?flow|sequence|flows?$")) return (GeneratedDocumentKind.DataFlow, "Data-flow file name");
        if (NameHas(@"architecture|components|containers|c4|topology")) return (GeneratedDocumentKind.Architecture, "Architecture file name");
        if (NameHas(@"^(readme|index|overview|about|summary)$")) return (GeneratedDocumentKind.Overview, "Overview file name");
        if (Mermaid("erDiagram")) return (GeneratedDocumentKind.DataModel, "Mermaid ER diagram");
        if (Mermaid("sequenceDiagram")) return (GeneratedDocumentKind.DataFlow, "Mermaid sequence diagram");
        if (Mermaid("(graph|flowchart|C4)")) return (GeneratedDocumentKind.Architecture, "Mermaid component diagram");
        if (structure.Tables.Any(t => DocumentStructure.Column(t, @"^(route|page route)$") >= 0)) return (GeneratedDocumentKind.Routes, "Route table");
        if (structure.Tables.Any(t => DocumentStructure.Column(t, @"^(topic|queue|subscription|event ?hub)s?$") >= 0)) return (GeneratedDocumentKind.Messaging, "Messaging resource table");
        if (structure.Headings.Any(h => Regex.IsMatch(h.Text, @"(?i)\bentit(y|ies)\b"))) return (GeneratedDocumentKind.DataModel, "Entity headings");
        return (GeneratedDocumentKind.OtherGeneratedDocumentation, "No kind signal in name or content");
    }

    /// <summary>Kind of a declared output from its file name only (no content exists for a missing document).</summary>
    public static GeneratedDocumentKind KindFromName(string fileName)
    {
        var ext = System.IO.Path.GetExtension(fileName).ToLowerInvariant();
        var name = System.IO.Path.GetFileNameWithoutExtension(fileName).ToLowerInvariant();
        if (ext is ".graphql" or ".graphqls" or ".gql") return GeneratedDocumentKind.GraphQlSchema;
        if (ext is ".yaml" or ".yml" or ".json") return Regex.IsMatch(name, "openapi|swagger") ? GeneratedDocumentKind.ApiContract : Regex.IsMatch(name, "asyncapi") ? GeneratedDocumentKind.Messaging : GeneratedDocumentKind.OtherGeneratedDocumentation;
        if (ext is ".xsd" or ".proto") return GeneratedDocumentKind.ApiContract;
        return Classify(fileName, "").Kind;
    }

    // ── helpers ──
    public static bool IsDocumentFile(string path)
    {
        var ext = System.IO.Path.GetExtension(path).ToLowerInvariant();
        return ext is ".md" or ".markdown" or ".mdx" or ".graphql" or ".graphqls" or ".gql" or ".xsd" or ".proto"
            || (ext is ".yaml" or ".yml" or ".json" && Regex.IsMatch(System.IO.Path.GetFileNameWithoutExtension(path), @"(?i)(openapi|swagger|asyncapi|api|schema)"));
    }

    public static string DirectoryOf(string path) => path.Contains('/') ? path[..path.LastIndexOf('/')] : "";
    public static string Leaf(string dir) => dir.Contains('/') ? dir[(dir.LastIndexOf('/') + 1)..] : dir;

    /// <summary>The scope a generated directory documents: its parent folder, skipping container folders (docs/, build/ …). "" = repository root.</summary>
    public static string ModuleRoot(string dir, GeneratedDocumentationOptions options)
    {
        var parent = DirectoryOf(dir);
        while (parent.Length > 0 && options.ContainerDirectories.Contains(Leaf(parent), StringComparer.OrdinalIgnoreCase)) parent = DirectoryOf(parent);
        return parent;
    }

    public static string Head(string content, int lines) => string.Join("\n", (content ?? "").Replace("\r\n", "\n").Split('\n').Take(lines));
    public static string Fingerprint(string content) => Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(content ?? ""))).ToLowerInvariant();
    public static string Safe(string value) => Integrations.SourceEvidence.IqrSourceArchiveReader.SafeLabel(value);
}
