using BirkNext.Api.Models;
using BirkNext.Api.Services;
using HotChocolate.Types;

namespace BirkNext.Api.GraphQL;

/// <summary>HotChocolate object type for a traceability suggestion with enriched titles.</summary>
public sealed class TraceabilitySuggestionItemObjectType : ObjectType<SuggestionItem>
{
    protected override void Configure(IObjectTypeDescriptor<SuggestionItem> descriptor)
    {
        descriptor.Name("TraceabilitySuggestionItem");
        descriptor.Description("A pending AI-suggested traceability link with source/target titles.");

        descriptor.Field(s => s.Suggestion)
            .Type<NonNullType<TraceabilitySuggestionObjectType>>()
            .Name("suggestion");

        descriptor.Field(s => s.SourceTitle)
            .Type<NonNullType<StringType>>()
            .Name("sourceTitle")
            .Description("Title of the source (test) scenario.");

        descriptor.Field(s => s.TargetTitle)
            .Type<NonNullType<StringType>>()
            .Name("targetTitle")
            .Description("Title of the target (requirement) scenario.");
    }
}

/// <summary>HotChocolate object type for <see cref="TraceabilitySuggestion"/>.</summary>
public sealed class TraceabilitySuggestionObjectType : ObjectType<TraceabilitySuggestion>
{
    protected override void Configure(IObjectTypeDescriptor<TraceabilitySuggestion> descriptor)
    {
        descriptor.Name("TraceabilitySuggestion");
        descriptor.Description("A pending traceability link suggestion generated by signal matching.");

        descriptor.Field(s => s.Id).Type<NonNullType<IdType>>();
        descriptor.Field(s => s.ProjectId).Type<NonNullType<StringType>>();
        descriptor.Field(s => s.SourceId).Type<NonNullType<IdType>>();
        descriptor.Field(s => s.SourceKind).Type<NonNullType<StringType>>();
        descriptor.Field(s => s.TargetId).Type<NonNullType<IdType>>();
        descriptor.Field(s => s.TargetKind).Type<NonNullType<StringType>>();
        descriptor.Field(s => s.LinkType).Type<NonNullType<StringType>>();
        descriptor.Field(s => s.Status).Type<NonNullType<StringType>>();
        descriptor.Field(s => s.Confidence).Type<NonNullType<FloatType>>();
        descriptor.Field(s => s.Reason).Type<NonNullType<StringType>>();
        descriptor.Field(s => s.SignalsJson).Type<NonNullType<StringType>>();
        descriptor.Field(s => s.CreatedAt).Type<NonNullType<DateTimeType>>();
        descriptor.Field(s => s.ConfirmedAt).Type<DateTimeType>();
        descriptor.Field(s => s.RejectedAt).Type<DateTimeType>();
    }
}

/// <summary>Summary of suggestion generation after Save Accepted.</summary>
public sealed class SuggestionGenerationResult
{
    public int TotalGenerated { get; init; }
    public int HighConfidenceCount { get; init; }
    public int NeedsReviewCount { get; init; }
    public bool SuggestionsAvailable { get; init; }
    public string? Message { get; init; }
}

public sealed class SuggestionGenerationResultObjectType : ObjectType<SuggestionGenerationResult>
{
    protected override void Configure(IObjectTypeDescriptor<SuggestionGenerationResult> descriptor)
    {
        descriptor.Name("SuggestionGenerationResult");
        descriptor.Description("Summary of traceability suggestions generated after saving artifacts.");

        descriptor.Field(s => s.TotalGenerated).Type<NonNullType<IntType>>();
        descriptor.Field(s => s.HighConfidenceCount).Type<NonNullType<IntType>>();
        descriptor.Field(s => s.NeedsReviewCount).Type<NonNullType<IntType>>();
        descriptor.Field(s => s.SuggestionsAvailable).Type<NonNullType<BooleanType>>();
        descriptor.Field(s => s.Message).Type<StringType>();
    }
}
