using Path = System.IO.Path;
using System.Globalization;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.RegularExpressions;
using BirkNext.PerformanceTests;

namespace BirkNext.Api.Services.PerformanceTests;

/// <summary>
/// Deterministic k6 script from a validated definition. Every user-supplied value (origin, paths, headers, bodies, test data, step names) enters
/// the script only as a JSON literal produced by System.Text.Json (which escapes quotes, backslashes, &lt;, &gt;, &amp;, U+2028/2029), so it cannot
/// escape a string or inject code. The same definition always yields the same script text.
/// </summary>
public static class K6ScriptGenerator
{
    private static readonly JsonSerializerOptions Json = new() { WriteIndented = false };

    public static string Generate(PerformanceTestDefinition d, PerformanceTestDataProfile? data, string summaryPath)
    {
        var steps = d.Scenario.Steps.Select(s => new JsonObject
        {
            ["name"] = s.Name, ["method"] = s.Method.ToUpperInvariant(), ["path"] = s.RelativePath,
            ["query"] = new JsonArray(s.QueryParameters.Select(q => (JsonNode)new JsonArray(q.Name, q.Value)).ToArray()),
            ["headers"] = new JsonObject(Headers(d, s).Select(h => KeyValuePair.Create(h.Key, (JsonNode?)h.Value))),
            ["body"] = Body(d, s), ["expected"] = new JsonArray(s.ExpectedStatusCodes.Distinct().Order().Select(c => (JsonNode)c).ToArray()),
            ["thinkMs"] = s.ThinkTimeMs ?? 0,
        }).ToList();
        var columns = data?.Columns ?? [];
        var rows = data?.Rows.Select(r => columns.Select((c, i) => (c, v: i < r.Count ? r[i] : "")).ToDictionary(x => x.c, x => x.v)).ToList() ?? [];
        var sb = new StringBuilder();
        sb.Append("// Generated by BirkNext from performance test definition ").Append(Lit(d.Id)).Append(" v").Append(d.Version).Append(". Do not edit.\n");
        sb.Append("import http from 'k6/http';\nimport { sleep } from 'k6';\nimport exec from 'k6/execution';\n");
        sb.Append("const ORIGIN = ").Append(Lit(d.TargetOrigin.TrimEnd('/'))).Append(";\n");
        sb.Append("const STEPS = ").Append(JsonSerializer.Serialize(steps, Json)).Append(";\n");
        sb.Append("const ROWS = ").Append(JsonSerializer.Serialize(rows, Json)).Append(";\n");
        sb.Append("const SELECTION = ").Append(Lit((data?.Selection ?? TestDataSelection.RoundRobin).ToString())).Append(";\n");
        sb.Append("const SUMMARY_PATH = ").Append(Lit(summaryPath)).Append(";\n");
        sb.Append("const thresholds = {};\nfor (const s of STEPS) {\n");
        sb.Append("  thresholds[`http_req_duration{name:${s.name}}`] = ['max>=0'];\n  thresholds[`http_req_failed{name:${s.name}}`] = ['rate>=0'];\n  thresholds[`http_reqs{name:${s.name}}`] = ['count>=0'];\n}\n");
        sb.Append("export const options = {\n  scenarios: { workload: ").Append(Scenario(d.Workload)).Append(" },\n");
        sb.Append("  thresholds,\n  summaryTrendStats: ['avg', 'min', 'med', 'max', 'p(90)', 'p(95)', 'p(99)'],\n  discardResponseBodies: true,\n};\n");
        sb.Append("""
            function row() {
              if (ROWS.length === 0) return {};
              let i;
              if (SELECTION === 'Sequential') i = exec.scenario.iterationInTest;
              else if (SELECTION === 'Random') i = Math.floor(Math.random() * ROWS.length);
              else if (SELECTION === 'UniquePerVirtualUser') i = exec.vu.idInTest - 1;
              else i = exec.vu.idInTest - 1 + exec.vu.iterationInInstance;
              return ROWS[i % ROWS.length];
            }
            function fill(text, r, encode) {
              if (text === null) return null;
              return text.replace(/\{([A-Za-z_][A-Za-z0-9_]*)\}/g, (m, k) => (Object.prototype.hasOwnProperty.call(r, k) ? (encode ? encodeURIComponent(r[k]) : r[k]) : m));
            }
            export default function () {
              const r = row();
              for (const s of STEPS) {
                const q = s.query.map(([k, v]) => `${encodeURIComponent(k)}=${encodeURIComponent(fill(v, r, false))}`).join('&');
                const url = ORIGIN + fill(s.path, r, true) + (q.length > 0 ? `?${q}` : '');
                http.request(s.method, url, fill(s.body, r, false), { headers: s.headers, tags: { name: s.name }, responseCallback: http.expectedStatuses(...s.expected) });
                if (s.thinkMs > 0) sleep(s.thinkMs / 1000);
              }
            }
            export function handleSummary(data) {
              const out = {};
              out[SUMMARY_PATH] = JSON.stringify({ birknext: 1, metrics: data.metrics, state: data.state });
              return out;
            }

            """);
        return sb.ToString();
    }

    /// <summary>One GET of the origin (1 VU, 1 iteration, 15 s timeout) recording the HTTP status and k6 error code — the container-network check.</summary>
    public static string Probe(string origin, string resultPath) =>
        "// Generated by BirkNext: container-network reachability check (one request). Do not edit.\n"
        + "import http from 'k6/http';\nimport { Trend } from 'k6/metrics';\n"
        + "const ORIGIN = " + Lit(origin.TrimEnd('/')) + ";\nconst OUT = " + Lit(resultPath) + ";\n"
        + "const status = new Trend('birknext_probe_status');\nconst code = new Trend('birknext_probe_error');\n"
        + "export const options = { vus: 1, iterations: 1, summaryTrendStats: ['max'] };\n"
        + "export default function () { const r = http.get(ORIGIN + '/', { timeout: '15s' }); status.add(r.status); code.add(r.error_code || 0); }\n"
        + "export function handleSummary(data) { const o = {}; o[OUT] = JSON.stringify({ birknext: 1, metrics: data.metrics }); return o; }\n";

    private static string Lit(string value) => JsonSerializer.Serialize(value, Json);

    private static IEnumerable<KeyValuePair<string, string>> Headers(PerformanceTestDefinition d, HttpPerformanceStep s)
    {
        var headers = s.Headers.Select(h => KeyValuePair.Create(h.Name, h.Value)).ToList();
        var contentType = d.TargetType == PerformanceTargetType.GraphQlHttp ? "application/json" : s.ContentType;
        if (contentType is not null && !headers.Any(h => h.Key.Equals("Content-Type", StringComparison.OrdinalIgnoreCase))) headers.Add(KeyValuePair.Create("Content-Type", contentType));
        return headers.OrderBy(h => h.Key, StringComparer.Ordinal);
    }

    private static string? Body(PerformanceTestDefinition d, HttpPerformanceStep s)
    {
        if (d.TargetType != PerformanceTargetType.GraphQlHttp) return s.BodyTemplate;
        var body = new JsonObject { ["query"] = s.GraphQlQuery ?? "" };
        if (!string.IsNullOrWhiteSpace(s.GraphQlOperationName)) body["operationName"] = s.GraphQlOperationName;
        if (!string.IsNullOrWhiteSpace(s.GraphQlVariablesJson)) body["variables"] = JsonNode.Parse(s.GraphQlVariablesJson);
        return body.ToJsonString(Json);
    }

    /// <summary>Generic workload → a k6 scenario. Virtual users → ramping-vus; arrival rate → ramping-arrival-rate per minute (integer rates).</summary>
    internal static string Scenario(PerformanceWorkload w)
    {
        string Stage(int seconds, double target) => $"{{ duration: '{seconds}s', target: {target.ToString(CultureInfo.InvariantCulture)} }}";
        var stages = new List<string>();
        if (w.Mode == WorkloadMode.VirtualUsers)
        {
            var vus = w.VirtualUsers ?? 1;
            var warm = PerformanceTestRules.WarmupVirtualUsers(w);
            if (w.WarmupSeconds > 0) stages.Add(Stage(w.WarmupSeconds, warm));
            if (w.RampUpSeconds > 0) stages.Add(Stage(w.RampUpSeconds, vus));
            if (w.SteadyStateSeconds > 0) stages.Add(Stage(w.SteadyStateSeconds, vus));
            if (w.RampDownSeconds > 0) stages.Add(Stage(w.RampDownSeconds, 0));
            return $"{{ executor: 'ramping-vus', startVUs: {(w.WarmupSeconds > 0 ? warm : 0)}, stages: [{string.Join(", ", stages)}], gracefulRampDown: '10s', gracefulStop: '10s' }}";
        }
        var target = (int)Math.Round((w.RequestsPerSecond ?? 1) * 60);
        var start = (int)Math.Round((w.StartRequestsPerSecond ?? Math.Max(1, (w.RequestsPerSecond ?? 1) / 10)) * 60);
        if (w.WarmupSeconds > 0) stages.Add(Stage(w.WarmupSeconds, start));
        if (w.RampUpSeconds > 0) stages.Add(Stage(w.RampUpSeconds, target));
        if (w.SteadyStateSeconds > 0) stages.Add(Stage(w.SteadyStateSeconds, target));
        if (w.RampDownSeconds > 0) stages.Add(Stage(w.RampDownSeconds, 0));
        var maxVus = Math.Max(1, w.VirtualUsers ?? 10);
        var pre = Math.Min(maxVus, Math.Max(1, (int)Math.Ceiling(w.RequestsPerSecond ?? 1)));
        return $"{{ executor: 'ramping-arrival-rate', startRate: {start}, timeUnit: '1m', preAllocatedVUs: {pre}, maxVUs: {maxVus}, stages: [{string.Join(", ", stages)}], gracefulStop: '10s' }}";
    }
}

/// <summary>Normalizes the k6 end-of-test summary into provider-independent metrics. Missing or malformed output is an error, never zero metrics.</summary>
public static class K6SummaryParser
{
    public static (PerformanceMetrics? Metrics, string? Error) Parse(string json, IReadOnlyList<string> stepNames)
    {
        JsonNode? root;
        try { root = JsonNode.Parse(json); }
        catch (JsonException) { return (null, "The k6 summary is not valid JSON."); }
        if (root?["metrics"] is not JsonObject metrics) return (null, "The k6 summary has no metrics section.");
        var reqs = Values(metrics, "http_reqs");
        var duration = Values(metrics, "http_req_duration");
        if (reqs is null || duration is null) return (null, "The k6 summary has no HTTP request metrics (no request was issued or the summary is incomplete).");
        var count = Long(reqs, "count") ?? 0;
        var failedValues = Values(metrics, "http_req_failed");
        // http_req_failed is a Rate: "passes" counts failed requests (value true), "fails" counts successful ones.
        long? failed = Long(failedValues, "passes");
        long? ok = Long(failedValues, "fails");
        var steps = stepNames.Distinct().Select(name =>
        {
            var d = Values(metrics, $"http_req_duration{{name:{name}}}");
            var f = Values(metrics, $"http_req_failed{{name:{name}}}");
            var r = Values(metrics, $"http_reqs{{name:{name}}}");
            return d is null || r is null ? null : new PerformanceStepMetrics(name, Long(r, "count") ?? 0, Double(f, "rate") is { } rate ? Math.Round(rate * 100, 3) : null,
                Double(d, "p(95)"), Double(d, "p(99)"), Double(r, "rate"));
        }).Where(s => s is not null).Cast<PerformanceStepMetrics>().ToList();
        var stateMs = root["state"]?["testRunDurationMs"]?.GetValue<double>();
        return (new PerformanceMetrics
        {
            RequestCount = count, FailedRequests = failed ?? 0, SuccessfulRequests = ok ?? Math.Max(0, count - (failed ?? 0)),
            ErrorRatePercent = Double(failedValues, "rate") is { } er ? Math.Round(er * 100, 3) : null,
            RequestsPerSecond = Double(reqs, "rate") is { } rps ? Math.Round(rps, 3) : null,
            DurationSeconds = stateMs is { } ms ? Math.Round(ms / 1000, 1) : 0,
            Latency = new PerformanceLatency
            {
                MinMs = Double(duration, "min"), MeanMs = Double(duration, "avg"), P50Ms = Double(duration, "med"), P90Ms = Double(duration, "p(90)"),
                P95Ms = Double(duration, "p(95)"), P99Ms = Double(duration, "p(99)"), MaxMs = Double(duration, "max"),
            },
            Steps = steps,
            DroppedIterations = Long(Values(metrics, "dropped_iterations"), "count"),
        }, null);
    }

    /// <summary>The probe's HTTP status (0 = no response) and k6 error code, or nulls when the result is unreadable.</summary>
    public static (int? Status, int? ErrorCode) Probe(string json)
    {
        try
        {
            if (JsonNode.Parse(json)?["metrics"] is not JsonObject metrics) return (null, null);
            return ((int?)Double(Values(metrics, "birknext_probe_status"), "max"), (int?)Double(Values(metrics, "birknext_probe_error"), "max"));
        }
        catch (JsonException) { return (null, null); }
    }

    private static JsonObject? Values(JsonObject metrics, string key) => metrics[key]?["values"] as JsonObject;

    private static double? Double(JsonObject? values, string key) =>
        values?[key] is JsonValue v && v.TryGetValue<double>(out var d) && double.IsFinite(d) ? Math.Round(d, 3) : null;

    private static long? Long(JsonObject? values, string key) => Double(values, key) is { } d ? (long)Math.Round(d) : null;
}
