using BirkNext.Integrations;

namespace BirkNext.Api.Services.ActiveEventTesting;

public sealed record ActiveEventProjectEvidenceContext(string TargetEnvironmentId, IntegrationDefinition? Integration, IntegrationPlatform? Platform);

public sealed record ActiveEventScenarioPreparation
{
    public bool Compatible { get; init; }
    public string Detail { get; init; } = "";
    public ActiveEventSourceContractReference Contract { get; init; } = new();
    public IReadOnlyList<ActiveEventReadinessCheck> Checks { get; init; } = [];
    public IReadOnlyDictionary<string, string> SafeMetadata { get; init; } = new Dictionary<string, string>();
}

public sealed record ActiveEventScenarioGeneration
{
    public IReadOnlyList<GeneratedActiveEvent> Events { get; init; } = [];
    public IReadOnlyDictionary<string, string> SafeMetadata { get; init; } = new Dictionary<string, string>();
    public IReadOnlyList<string> Limitations { get; init; } = [];
}

/// <summary>Project/domain extension: decides applicability, validates its source contract, and creates bounded synthetic events.</summary>
public interface IActiveEventScenarioProvider
{
    string ExtensionId { get; }
    string ExtensionVersion { get; }
    bool CanApply(ActiveEventProjectEvidenceContext context);
    IReadOnlyList<ActiveEventScenarioDescriptor> GetScenarios(ActiveEventProjectEvidenceContext context);
    Task<ActiveEventScenarioPreparation> PrepareAsync(string scenarioId, ActiveEventProjectEvidenceContext context, Guid? sourceSnapshotId, CancellationToken ct);
    Task<ActiveEventScenarioGeneration> GenerateAsync(string scenarioId, Guid runId, ActiveEventTrustedTarget target,
        ActiveEventSourceContractReference contract, CancellationToken ct);
}

public interface IActiveEventScenarioRegistry
{
    IReadOnlyList<IActiveEventScenarioProvider> Applicable(ActiveEventProjectEvidenceContext context);
    IActiveEventScenarioProvider? Find(string extensionId);
    IActiveEventScenarioProvider? FindScenario(string scenarioId, ActiveEventProjectEvidenceContext context);
    IReadOnlyList<ActiveEventScenarioDescriptor> Scenarios(ActiveEventProjectEvidenceContext context);
}

public sealed class ActiveEventScenarioRegistry(IEnumerable<IActiveEventScenarioProvider> providers) : IActiveEventScenarioRegistry
{
    private readonly IReadOnlyList<IActiveEventScenarioProvider> _providers = providers.OrderBy(p => p.ExtensionId, StringComparer.Ordinal).ToArray();
    public IReadOnlyList<IActiveEventScenarioProvider> Applicable(ActiveEventProjectEvidenceContext context) => _providers.Where(p => p.CanApply(context)).ToArray();
    public IActiveEventScenarioProvider? Find(string extensionId) => _providers.FirstOrDefault(p => string.Equals(p.ExtensionId, extensionId, StringComparison.Ordinal));
    public IActiveEventScenarioProvider? FindScenario(string scenarioId, ActiveEventProjectEvidenceContext context) => Scenarios(context)
        .Where(descriptor => string.Equals(descriptor.ScenarioId, scenarioId, StringComparison.Ordinal))
        .Select(descriptor => Applicable(context).Single(provider => provider.GetScenarios(context).Any(item => item.ScenarioId == descriptor.ScenarioId)))
        .SingleOrDefault();

    public IReadOnlyList<ActiveEventScenarioDescriptor> Scenarios(ActiveEventProjectEvidenceContext context)
    {
        var scenarios = Applicable(context).SelectMany(provider => provider.GetScenarios(context)).ToArray();
        var duplicate = scenarios.GroupBy(item => item.ScenarioId, StringComparer.Ordinal).FirstOrDefault(group => group.Count() > 1);
        if (duplicate is not null) throw new InvalidOperationException($"Duplicate Active Event scenario ID '{duplicate.Key}'. Scenario IDs must be unique across registered extensions.");
        return scenarios;
    }
}

/// <summary>Technology extension: sends opaque generated bytes to a trusted target without interpreting their domain.</summary>
public interface IActiveEventTransportProvider
{
    string TransportType { get; }
    bool CanSend(ActiveEventTrustedTarget target, out string reason);
    Task<ActiveEventStageEvidence> SendAsync(ActiveEventTrustedTarget target, GeneratedActiveEvent activeEvent, TimeSpan timeout, CancellationToken ct);
}

public interface IActiveEventTransportRegistry
{
    IActiveEventTransportProvider? Resolve(string transportType);
}

public sealed class ActiveEventTransportRegistry(IEnumerable<IActiveEventTransportProvider> providers) : IActiveEventTransportRegistry
{
    private readonly IReadOnlyDictionary<string, IActiveEventTransportProvider> _providers = BuildProviders(providers);
    public IActiveEventTransportProvider? Resolve(string transportType) => _providers.GetValueOrDefault(transportType);

    private static IReadOnlyDictionary<string, IActiveEventTransportProvider> BuildProviders(IEnumerable<IActiveEventTransportProvider> providers)
    {
        var items = providers.ToArray();
        var duplicate = items.GroupBy(provider => provider.TransportType, StringComparer.OrdinalIgnoreCase).FirstOrDefault(group => group.Count() > 1);
        if (duplicate is not null) throw new InvalidOperationException($"Duplicate Active Event transport provider '{duplicate.Key}'.");
        return items.ToDictionary(provider => provider.TransportType, StringComparer.OrdinalIgnoreCase);
    }
}

public interface IActiveEventTrustedTargetResolver
{
    Task<ActiveEventTrustedTarget?> ResolveAsync(string targetEnvironmentId, string integrationId, CancellationToken ct);
}

public sealed record ActiveEventSafetyDecision(bool Allowed, string Reason, ActiveEventTrustedTarget? Target = null);

public interface IActiveEventSafetyPolicy
{
    ActiveEventSafetyDecision Evaluate(ActiveEventScenarioDescriptor scenario, ActiveEventTrustedTarget? target,
        ActiveEventScenarioPreparation? preparation, bool confirmed);
}

public interface IActiveEventConsumerEvidenceProvider
{
    bool CanObserve(ActiveEventTrustedTarget target, ActiveEventCorrelation correlation, out string reason);
    Task<ActiveEventStageEvidence> ObserveAsync(ActiveEventTrustedTarget target, ActiveEventCorrelation correlation, TimeSpan window, CancellationToken ct);
}

public interface IConsumerContinuityEvidenceProvider
{
    bool CanObserve(ActiveEventTrustedTarget target, out string reason);
    Task<ActiveEventStageEvidence> ObserveAsync(ActiveEventTrustedTarget target, ActiveEventCorrelation correlation,
        DateTimeOffset since, TimeSpan window, CancellationToken ct);
}

public interface IActiveEventDownstreamVerifier
{
    bool CanVerify(ActiveEventTrustedTarget target, ActiveEventScenarioDescriptor scenario, out string reason);
    Task<ActiveEventStageEvidence> VerifyAsync(ActiveEventTrustedTarget target, ActiveEventScenarioDescriptor scenario,
        ActiveEventCorrelation correlation, CancellationToken ct);
}
