using System.Text.RegularExpressions;
using BirkNext.RealProjectAcceptance;
using Microsoft.Playwright;

namespace BirkNext.Web.PlaywrightTests.RealProjectAcceptance.Features;

/// <summary>
/// AI-Generated Code Review over the run's imported snapshot: the page preselects that snapshot, the deterministic review runs, categories are
/// honest (findings / no indicators / not assessed / unsupported / not applicable), findings carry provenance, nothing claims authorship,
/// export works, and the page holds up at four widths, under axe and with the keyboard.
/// </summary>
public sealed class AiGeneratedCodeReviewFeature : AcceptanceFeature
{
    public override string FeatureId => "ai-generated-code-review";
    public override string DisplayName => "AI-Generated Code Review";
    public override string Area => "Quality & Testing";
    public override string Route => "/ai-generated-code-review";
    public override IReadOnlyList<string> RequiredEvidence => ["Source Analysis snapshot"];
    public override IReadOnlyList<string> DependsOn => [ImportFeatureId, "source-analysis"];

    private static readonly string[] AuthorshipClaims = ["this code is ai-generated", "was generated by ai", "ai wrote this", "authored by ai", "hallucinated this"];

    protected override async Task RunAsync(RealProjectAcceptanceContext context, PlaywrightAcceptanceSession session, FeatureResultBuilder result, CancellationToken ct)
    {
        await OpenAsync(session, result);
        if (await session.WaitAnyAsync(60_000, "[data-testid=aic-current]", "[data-testid=aic-source-empty]") != "[data-testid=aic-current]")
        {
            result.Defect("aic-no-snapshot", "AI-Generated Code Review offers no Source Analysis snapshot although the import created one.");
            result.Evidence = EvidenceState.NotVerified;
            return;
        }
        var selected = await session.Page.Locator("[data-testid=aic-current]").InputValueAsync();
        RecordIdentity(context, FeatureId, "snapshot", selected);
        result.Observe("preselected snapshot", selected);
        if (!string.Equals(selected, context.Workspace.SourceSnapshotId, StringComparison.OrdinalIgnoreCase))
            result.Defect("aic-wrong-snapshot", "The page did not preselect the imported project's snapshot.");
        result.Observe("upload controls", await session.CountAsync("[data-testid=aic-page] input[type=file]"));
        if (await session.CountAsync("[data-testid=aic-page] input[type=file]") > 0) result.Defect("aic-upload", "The review offers a source upload; source must come from Source Analysis.");

        var idleAxe = await session.AxeAsync("[data-testid=aic-page]");
        foreach (var v in idleAxe) result.Warn("axe", $"readiness state: {v}");

        var watch = System.Diagnostics.Stopwatch.StartNew();
        await session.Page.Locator("[data-testid=aic-run]").ClickAsync();
        var state = await session.WaitAnyAsync(300_000, "[data-testid=aic-result]", "[data-testid=aic-error]");
        result.Observe("review duration", $"{watch.Elapsed.TotalSeconds:0.0} s");
        if (state != "[data-testid=aic-result]")
        {
            result.Execution = ExecutionStatus.Failed;
            result.Defect("aic-run-failed", await session.TextAsync("[data-testid=aic-error]") is { Length: > 0 } e ? e : "The review did not complete.");
            return;
        }

        var categories = await session.Page.Locator("[data-testid=aic-category]").EvaluateAllAsync<string[]>("els => els.map(e => e.getAttribute('data-category') + '=' + e.getAttribute('data-status'))");
        var findings = await session.CountAsync("[data-testid=aic-finding]");
        var rules = await session.Page.Locator("[data-testid=aic-rule]").EvaluateAllAsync<string[]>("els => els.map(e => e.getAttribute('data-state'))");
        result.Observe("categories", string.Join(", ", categories)).Observe("findings shown", findings).Observe("summary", await session.TextAsync("[data-testid=aic-summary]"))
            .Observe("rules", string.Join(", ", rules.GroupBy(r => r).Select(g => $"{g.Key} {g.Count()}")));
        if (categories.Length < 13) result.Defect("aic-categories", $"Only {categories.Length} review categories were shown.");
        if (rules.Length == 0 || rules.All(r => r != "Executed")) result.Defect("aic-no-rules-executed", "No review rule executed against the real snapshot.");
        if (!categories.Any(c => c.EndsWith("=NotAssessed") || c.EndsWith("=Unsupported") || c.EndsWith("=NotApplicable")))
            result.Warn("aic-all-assessed", "Every category claims an assessment; expected some Not assessed/Unsupported/Not applicable states for a single-snapshot review.");

        // Provenance: the first finding's details must name evidence and an affected location or related id.
        if (findings > 0)
        {
            var first = session.Page.Locator("[data-testid=aic-finding]").First;
            await first.Locator("summary").ClickAsync();
            var detail = await first.Locator("[data-testid=aic-finding-detail]").InnerTextAsync();
            result.Observe("first finding", (await first.Locator("summary").InnerTextAsync()).Replace('\n', ' '));
            if (!detail.Contains("Evidence", StringComparison.Ordinal) || !(detail.Contains("Affected source", StringComparison.Ordinal) || detail.Contains("Related", StringComparison.Ordinal)))
                result.Defect("aic-provenance", "A finding does not show its evidence and location/related ids.");
            var keyboardFocus = await first.Locator("summary").EvaluateAsync<bool>("s => { s.focus(); return document.activeElement === s; }");
            result.Observe("finding summary keyboard-focusable", keyboardFocus);
            if (!keyboardFocus) result.Warn("aic-keyboard", "The finding expansion control cannot receive focus.");
            result.Fact([.. categories.Select(c => c.Split('=')[0])]);
        }
        var body = (await session.Page.Locator("[data-testid=aic-page]").InnerTextAsync()).ToLowerInvariant();
        foreach (var claim in AuthorshipClaims.Where(body.Contains)) result.Defect("aic-authorship-claim", $"The page claims authorship: \"{claim}\".");
        if (Regex.IsMatch(body, @"\b(ai|quality|confidence|risk)\s*(score)?\s*:?\s*\d{1,3}\s*%")) result.Defect("aic-score", "An AI score or percentage is shown.");
        var limitations = await session.TextAsync("[data-testid=aic-limitations]");
        result.Observe("limitations", limitations.Length > 300 ? limitations[..300] + "…" : limitations);

        foreach (var v in await session.AxeAsync("[data-testid=aic-page]")) result.Warn("axe", $"completed review: {v}");
        await Keyboard(session, result);
        await Responsive(session, result);
        result.DataFromCount(rules.Count(r => r == "Executed"), DataState.NotAssessed);
        result.Provenance = string.Equals(selected, context.Workspace.SourceSnapshotId, StringComparison.OrdinalIgnoreCase) ? ProvenanceState.Traced : ProvenanceState.Missing;
        await ExportAsync(session, result, session.Page.Locator("[data-testid=aic-export]"), context);
    }

    private static async Task Keyboard(PlaywrightAcceptanceSession session, FeatureResultBuilder result)
    {
        await session.Page.Locator("[data-testid=aic-current]").FocusAsync();
        var reached = new List<string>();
        for (var i = 0; i < 12; i++)
        {
            await session.Page.Keyboard.PressAsync("Tab");
            var id = await session.Page.EvaluateAsync<string?>("() => document.activeElement?.getAttribute('data-testid')");
            if (id is not null) reached.Add(id);
            var visible = await session.Page.EvaluateAsync<bool>("() => { const e = document.activeElement; if (!e) return false; const s = getComputedStyle(e); return s.outlineStyle !== 'none' || s.boxShadow !== 'none'; }");
            if (id is "aic-run" && !visible) result.Warn("aic-focus-visible", "The run button has no visible focus indicator.");
        }
        result.Observe("keyboard order", string.Join(" → ", reached.Distinct()));
        foreach (var expected in new[] { "aic-baseline", "aic-run" })
            if (!reached.Contains(expected) && !(expected == "aic-baseline" && await session.Page.Locator("[data-testid=aic-baseline]").IsDisabledAsync()))
                result.Warn("aic-keyboard", $"{expected} was not reached with the Tab key.");
    }

    private static async Task Responsive(PlaywrightAcceptanceSession session, FeatureResultBuilder result)
    {
        var overflowing = new List<int>();
        try
        {
            foreach (var width in new[] { 1440, 1100, 768, 390 })
            {
                await session.Page.SetViewportSizeAsync(width, 1000);
                await session.Page.WaitForTimeoutAsync(400);
                var (client, scroll) = await session.HorizontalExtentAsync();
                if (scroll > client + 1) { overflowing.Add(width); result.Warn("horizontal-overflow", $"AI-Generated Code Review overflows at {width}px ({scroll}px > {client}px)."); }
            }
        }
        finally { await session.Page.SetViewportSizeAsync(1440, 1000); }
        result.Observe("widths checked", "1440, 1100, 768, 390").Observe("overflowing widths", overflowing.Count == 0 ? "none" : string.Join(", ", overflowing));
    }
}
