using System.Text.Json.Serialization;

namespace BirkNext.Integrations;

/// <summary>Transport-neutral event concepts used by Active Event Testing.</summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum ActiveEventOperation { Create, Update, Delete, ReadSnapshot, Tombstone, Custom }

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum ActiveEventReplayKind { None, ExactReplay, NaturalKeyDuplicate, ControlAfterInvalid }

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum ActiveEventEvidenceStage
{
    Generated, SendAttempted, TransportAccepted, ConsumerActivityObserved, ConsumerContinuityObserved, DownstreamPersistenceVerified
}

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum ActiveEventEvidenceStatus { NotAttempted, Observed, NotObserved, NotVerified, Unavailable, Ambiguous, Failed, SafetyBlocked }

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum ActiveEventRunStatus { Running, Completed, CompletedWithLimitedEvidence, Failed, SafetyBlocked, Inconclusive, Cancelled }

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum ActiveEventReadinessState { Ready, Blocked, Unknown, Optional }

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum ActiveEventCorrelationQuality { Exact, Strong, Moderate, Weak, AggregateOnly, Unavailable }

/// <summary>Project extension declaration. Domain-specific requirements live in extension providers, not the execution engine.</summary>
public sealed record ActiveEventScenarioDescriptor
{
    public string ExtensionId { get; init; } = "";
    public string ExtensionVersion { get; init; } = "";
    public string ScenarioId { get; init; } = "";
    public string ScenarioVersion { get; init; } = "";
    public string DisplayName { get; init; } = "";
    public string Description { get; init; } = "";
    public string Category { get; init; } = "";
    public string RequiredIntegrationType { get; init; } = "";
    public string RequiredTransportType { get; init; } = "";
    public IReadOnlyList<ActiveEventOperation> SupportedOperations { get; init; } = [];
    public int ExpectedEventCount { get; init; } = 1;
    public bool SyntheticDataRequired { get; init; } = true;
    public ActiveEventReplayKind ReplayKind { get; init; }
    public IReadOnlyList<string> RequiredSourceEvidence { get; init; } = [];
    public IReadOnlyList<string> VerificationCapabilities { get; init; } = [];
}

public sealed record ActiveEventReadinessCheck(string Key, string Label, ActiveEventReadinessState State, string Detail);

public sealed record ActiveEventReadiness
{
    public string TargetEnvironmentId { get; init; } = "";
    public string IntegrationId { get; init; } = "";
    public ActiveEventScenarioDescriptor Scenario { get; init; } = new();
    public ActiveEventTrustedTarget? Target { get; init; }
    public ActiveEventSourceContractReference SourceContract { get; init; } = new();
    public IReadOnlyList<ActiveEventReadinessCheck> Checks { get; init; } = [];
    public bool CanRun { get; init; }
    public int SendTimeoutSeconds { get; init; }
    public int ObservationTimeoutSeconds { get; init; }
}

public sealed record ActiveEventRunRequest
{
    public string TargetEnvironmentId { get; init; } = "";
    public string IntegrationId { get; init; } = "";
    public string ExtensionId { get; init; } = "";
    public string ScenarioId { get; init; } = "";
    public Guid? SourceSnapshotId { get; init; }
    public bool Confirmed { get; init; }
    public string? ConfirmedDestination { get; init; }
}

/// <summary>Correlation metadata safe to persist; raw event bodies and secrets are never part of this contract.</summary>
public sealed record ActiveEventCorrelation
{
    public Guid RunId { get; init; }
    public string EventId { get; init; } = "";
    public string EventFingerprint { get; init; } = "";
    public string SyntheticMarker { get; init; } = "";
    public string? SafeSourceIdentity { get; init; }
    public IReadOnlyDictionary<string, string> ExtensionValues { get; init; } = new Dictionary<string, string>();
    public string? ReplaysEventId { get; init; }
    public ActiveEventReplayKind ReplayKind { get; init; }
}

/// <summary>Opaque extension-generated bytes plus safe metadata. The core must not inspect Body.</summary>
public sealed record GeneratedActiveEvent
{
    public string EventId { get; init; } = "";
    public string ExtensionId { get; init; } = "";
    public string ScenarioId { get; init; } = "";
    public int SequenceIndex { get; init; }
    public ActiveEventOperation Operation { get; init; }
    public byte[] Body { get; init; } = [];
    public string BodySha256 { get; init; } = "";
    public int BodyBytes { get; init; }
    public string ContentType { get; init; } = "application/octet-stream";
    public ActiveEventCorrelation Correlation { get; init; } = new();
    public IReadOnlyDictionary<string, string> SafeDisplayMetadata { get; init; } = new Dictionary<string, string>();
    public IReadOnlyDictionary<string, string> TransportProperties { get; init; } = new Dictionary<string, string>();
}

public sealed record ActiveEventStageEvidence
{
    public ActiveEventEvidenceStage Stage { get; init; }
    public ActiveEventEvidenceStatus Status { get; init; } = ActiveEventEvidenceStatus.NotVerified;
    public ActiveEventCorrelationQuality CorrelationQuality { get; init; } = ActiveEventCorrelationQuality.Unavailable;
    public string Detail { get; init; } = "";
    public string EvidenceSource { get; init; } = "";
    public DateTimeOffset? CapturedAt { get; init; }
}

public sealed record ActiveEventTrustedTarget
{
    public string TargetEnvironmentId { get; init; } = "";
    public string EnvironmentType { get; init; } = "Unknown";
    public string IntegrationId { get; init; } = "";
    public string IntegrationType { get; init; } = "";
    public string TransportType { get; init; } = "";
    public string? Endpoint { get; init; }
    public string? Resource { get; init; }
    public string? Consumer { get; init; }
    public string AuthenticationMode { get; init; } = "Instance identity";
    public IReadOnlyDictionary<string, string> SafeMetadata { get; init; } = new Dictionary<string, string>();
}

public sealed record ActiveEventSourceContractReference
{
    public Guid? SourceSnapshotId { get; init; }
    public string? ContractFingerprint { get; init; }
    public string? SourceResource { get; init; }
    public string ExtensionVersion { get; init; } = "";
    public string ScenarioVersion { get; init; } = "";
}

/// <summary>Safe event summary for durable history. Event bodies are intentionally excluded.</summary>
public sealed record ActiveEventGeneratedSummary
{
    public string EventId { get; init; } = "";
    public string ExtensionId { get; init; } = "";
    public string ScenarioId { get; init; } = "";
    public int SequenceIndex { get; init; }
    public ActiveEventOperation Operation { get; init; }
    public string ContentType { get; init; } = "application/octet-stream";
    public string BodySha256 { get; init; } = "";
    public int BodyBytes { get; init; }
    public ActiveEventCorrelation Correlation { get; init; } = new();
    public IReadOnlyDictionary<string, string> SafeMetadata { get; init; } = new Dictionary<string, string>();
}

/// <summary>Transport-neutral immutable run/history contract. This is the lifecycle result shared by every scenario extension.</summary>
public sealed record ActiveEventRunResult
{
    public Guid RunId { get; init; }
    public ActiveEventScenarioDescriptor Scenario { get; init; } = new();
    public ActiveEventTrustedTarget Target { get; init; } = new();
    public ActiveEventSourceContractReference SourceContract { get; init; } = new();
    public ActiveEventRunStatus Status { get; init; } = ActiveEventRunStatus.Running;
    public DateTimeOffset StartedAt { get; init; }
    public DateTimeOffset? CompletedAt { get; init; }
    public IReadOnlyList<ActiveEventGeneratedSummary> Events { get; init; } = [];
    public IReadOnlyList<ActiveEventStageEvidence> Evidence { get; init; } = [];
    public IReadOnlyList<string> Limitations { get; init; } = [];
}
