using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using BirkNext.Api.Models;
using BirkNext.Api.Services.Integrations.SourceEvidence;
using BirkNext.Api.Services.SourceAnalysis.GeneratedDocumentation;
using BirkNext.GeneratedDocumentation;
using BirkNext.SourceArchitecture;
using FluentAssertions;
using Microsoft.Extensions.Caching.Memory;
using static BirkNext.Api.Tests.Services.SourceAnalysis.GeneratedDocumentation.GeneratedDocumentationFixture;

namespace BirkNext.Api.Tests.Services.SourceAnalysis.GeneratedDocumentation;

/// <summary>
/// Generated documentation is its own evidence type: detection and provenance, module-scoped freshness, expected outputs, generated-vs-source
/// drift, authored drift (specification, constitution, plan, delivery), snapshot binding and project isolation. Generic fixtures only.
/// </summary>
public sealed class GeneratedDocumentationEvidenceTests
{
    private const string Root = "shop/orders";

    // ── Detection and provenance ──

    [Fact]
    public async Task Generator_workflow_that_declares_the_output_folder_is_the_provenance()
    {
        using var db = Db();
        var snapshot = await AnalyzeAsync(db, Orders());
        var g = snapshot.GeneratedDocumentation!;
        g.SourceSnapshotId.Should().Be(snapshot.Id);
        var workflow = g.Generators.Single(w => w.Path == ".claude/skills/doc-writer/SKILL.md");
        workflow.Type.Should().Be(GeneratorType.AgentWorkflow);
        workflow.GeneratorName.Should().Be("doc-writer");
        workflow.DeclaredOutputDirectories.Should().Contain("generated-docs/");
        workflow.DeclaredOutputFiles.Should().Contain(["README.md", "openapi.yaml", "message-bus.md"]);
        var readme = Doc(snapshot, $"{Root}/generated-docs/README.md");
        readme.Origin.Should().Be(DocumentationOrigin.Generated);
        readme.DocumentKind.Should().Be(GeneratedDocumentKind.Overview);
        readme.Provenance.GeneratorType.Should().Be(GeneratorType.AgentWorkflow);
        readme.Provenance.GeneratorName.Should().Be("doc-writer");
        readme.Provenance.Confidence.Should().Be(ArchitectureEvidenceState.Confirmed);
        readme.Provenance.DetectedFrom.Should().Contain(d => d.Contains(".claude/skills/doc-writer/SKILL.md"));
        Doc(snapshot, $"{Root}/generated-docs/openapi.yaml").DocumentKind.Should().Be(GeneratedDocumentKind.ApiContract);
        Doc(snapshot, $"{Root}/generated-docs/data-model.md").DocumentKind.Should().Be(GeneratedDocumentKind.DataModel);
        // Authored Spec-Kit artifacts are never generated documentation, and nothing is stored as text.
        g.Documents.Should().NotContain(d => d.SafeRelativePath.Contains("/specs/") || d.SafeRelativePath.EndsWith("constitution.md"));
        JsonSerializer.Serialize(g).Should().NotContain("Orders service. Technology");
    }

    [Fact]
    public async Task Without_a_workflow_the_folder_convention_gives_unknown_provenance_never_a_fabricated_generator()
    {
        using var db = Db();
        var snapshot = await AnalyzeAsync(db, Orders(workflow: false));
        snapshot.GeneratedDocumentation!.Generators.Should().BeEmpty();
        var readme = Doc(snapshot, $"{Root}/generated-docs/README.md");
        readme.Provenance.GeneratorType.Should().Be(GeneratorType.Unknown);
        readme.Provenance.GeneratorName.Should().BeNull();
        readme.Provenance.Label.Should().Be("Likely generated / Unknown provenance");
        readme.Provenance.Confidence.Should().Be(ArchitectureEvidenceState.Inferred);
        var run = await Diagnostic(db).RunAsync(new GeneratedDocumentationDiagnosticRequest());
        var module = run.Modules.Single(m => m.RootPath == Root);
        module.GeneratorDetected.Should().BeFalse();
        module.Status.Should().NotBe(GeneratedDocumentationHealthStatus.Fail);
        run.Summary.ModulesWithGeneratorDetected.Should().Be(0);
    }

    [Fact]
    public async Task Ordinary_docs_and_agent_context_files_are_not_generated_documentation()
    {
        using var db = Db();
        var files = Orders();
        files.Add(("shop/docs/guide.md", "# Guide\n\nHow to run the shop.\n"));
        files.Add(("shop/orders/CLAUDE.md", "# Shop Development Guidelines\n\nAuto-generated from all feature plans.\n"));
        files.Add(("shop/orders/docs/changes.md", "<!-- generated by release-notes -->\n# Changes\n"));
        var snapshot = await AnalyzeAsync(db, files);
        var paths = snapshot.GeneratedDocumentation!.Documents.Select(d => d.SafeRelativePath).ToList();
        paths.Should().NotContain(["shop/docs/guide.md", "shop/orders/CLAUDE.md"]);
        // An explicit generated marker is a (weaker) signal on its own; its provenance stays unknown.
        Doc(snapshot, "shop/orders/docs/changes.md").Provenance.Label.Should().Be("Likely generated / Unknown provenance");
    }

    // ── Freshness ──

    [Fact]
    public async Task Fresh_when_the_relevant_dated_source_evidence_is_older_than_the_declared_generation_date()
    {
        using var db = Db();
        var snapshot = await AnalyzeAsync(db, Orders(generatedDate: "2026-03-01", migrationId: "20260201090000"));
        var dataModel = Doc(snapshot, $"{Root}/generated-docs/data-model.md");
        dataModel.FreshnessStatus.Should().Be(GeneratedDocumentationFreshnessStatus.Current);
        dataModel.LastModified!.Basis.Should().StartWith("Declared in the document");
        dataModel.SourceLastModified!.Basis.Should().Contain("Migration");
    }

    [Fact]
    public async Task Potentially_stale_when_relevant_source_changed_after_generation()
    {
        using var db = Db();
        var snapshot = await AnalyzeAsync(db, Orders(generatedDate: "2026-03-01", migrationId: "20260415090000"));
        Doc(snapshot, $"{Root}/generated-docs/data-model.md").FreshnessStatus.Should().Be(GeneratedDocumentationFreshnessStatus.Stale);
        var module = Module(snapshot, Root);
        module.Freshness.Should().Be(GeneratedDocumentationFreshnessStatus.Stale);
        module.FreshnessReason.Should().Contain("2026-04-15");
        GeneratedDocumentationText.Label(module.Freshness).Should().Be("Potentially stale");
    }

    [Fact]
    public async Task Uniform_archive_times_and_no_declared_date_give_unknown_never_stale()
    {
        using var db = Db();
        var files = Orders(migrationId: "20260415090000").Select(f => f.Path.EndsWith("data-model.md") ? (f.Path, f.Content.Replace("Last updated: 2026-03-01", "")) : f).ToList();
        var snapshot = await AnalyzeAsync(db, files);
        snapshot.GeneratedDocumentation!.ArchiveTimestampsReliable.Should().BeFalse();
        var dataModel = Doc(snapshot, $"{Root}/generated-docs/data-model.md");
        dataModel.FreshnessStatus.Should().Be(GeneratedDocumentationFreshnessStatus.Unknown);
        Module(snapshot, Root).Freshness.Should().NotBe(GeneratedDocumentationFreshnessStatus.Stale);
        // Overview documents have a declared date but no trustworthy dated source evidence: not enough evidence, not stale.
        Doc(snapshot, $"{Root}/generated-docs/README.md").FreshnessStatus.Should().Be(GeneratedDocumentationFreshnessStatus.NotEnoughEvidence);
    }

    [Fact]
    public async Task Varied_archive_times_are_used_and_scoped_to_the_module()
    {
        using var db = Db();
        var files = Orders(generatedDate: "2026-03-01");
        // A second module whose source changed after the orders documentation was generated.
        files.AddRange([
            ("shop/billing/src/Shop.Billing.Api/Shop.Billing.Api.csproj", Csproj),
            ("shop/billing/src/Shop.Billing.Api/Program.cs", Program("/invoices")),
            ("shop/billing/generated-docs/README.md", "Last updated: 2026-03-01\n\n# Shop.Billing\n"),
        ]);
        var snapshot = await AnalyzeAsync(db, files, path =>
            path.StartsWith("shop/billing/src", StringComparison.Ordinal) ? new DateTimeOffset(2026, 4, 20, 10, 0, 0, TimeSpan.Zero)
            : path.Contains("generated-docs") ? new DateTimeOffset(2026, 3, 1, 9, 0, 0, TimeSpan.Zero)
            : new DateTimeOffset(2026, 2, 10, 9, (path.Length % 50), 0, TimeSpan.Zero));
        snapshot.GeneratedDocumentation!.ArchiveTimestampsReliable.Should().BeTrue();
        Module(snapshot, "shop/billing").Freshness.Should().Be(GeneratedDocumentationFreshnessStatus.Stale);
        // Billing's newer source never dates the orders documentation.
        Module(snapshot, Root).Freshness.Should().Be(GeneratedDocumentationFreshnessStatus.Current);
    }

    // ── Expected outputs ──

    [Fact]
    public async Task Missing_expected_document_only_where_the_module_shows_the_capability_and_extra_documents_are_not_failures()
    {
        using var db = Db();
        var files = Orders().Where(f => !f.Path.EndsWith("openapi.yaml")).ToList();
        files.Add(($"{Root}/generated-docs/review-notes.md", "# Review notes\n"));
        var snapshot = await AnalyzeAsync(db, files);
        var module = Module(snapshot, Root);
        module.MissingExpectedDocs.Should().Contain("openapi.yaml");
        // Declared, but the module has no messaging code: not expected.
        module.MissingExpectedDocs.Should().NotContain("message-bus.md");
        module.ExpectedDocuments.Single(e => e.FileName == "message-bus.md").CapabilityPresent.Should().BeFalse();
        module.AdditionalDocs.Should().Contain($"{Root}/generated-docs/review-notes.md");
        Doc(snapshot, $"{Root}/generated-docs/review-notes.md").Origin.Should().Be(DocumentationOrigin.Unknown);
        var run = await Diagnostic(db).RunAsync(new GeneratedDocumentationDiagnosticRequest());
        var health = run.Modules.Single(m => m.RootPath == Root);
        health.Status.Should().Be(GeneratedDocumentationHealthStatus.Warning);
        run.Summary.MissingExpectedDocs.Should().Be(1);
    }

    // ── Generated vs source ──

    [Fact]
    public async Task Matching_generated_and_source_routes_give_no_drift()
    {
        using var db = Db();
        var snapshot = await AnalyzeAsync(db, Orders(documentedRoutes: ["/orders"], sourceRoutes: ["/orders"]));
        Module(snapshot, Root).Comparisons.Single(c => c.Family == "HTTP routes").State.Should().Be(GeneratedComparisonState.Equivalent);
        snapshot.GeneratedDocumentation!.Drift.Should().NotContain(d => d.Family == "HTTP routes");
    }

    [Fact]
    public async Task A_documented_route_missing_from_source_is_a_potential_documentation_drift_requiring_review()
    {
        using var db = Db();
        var snapshot = await AnalyzeAsync(db, Orders(documentedRoutes: ["/orders", "/invoices"], sourceRoutes: ["/orders"]));
        var drift = snapshot.GeneratedDocumentation!.Drift.Single(d => d.Family == "HTTP routes");
        drift.DriftType.Should().Be(CrossArtifactDriftType.DocumentationDrift);
        drift.DifferenceKind.Should().Be(DriftDifferenceKind.MissingOnRight);
        drift.StructuredKey.Should().Be("GET /invoices");
        drift.ReviewRequired.Should().BeTrue();
        drift.ReviewStatus.Should().Be(DriftReviewStatus.NeedsReview);
        drift.SourceSnapshotId.Should().Be(snapshot.Id);
        drift.LeftEvidence.Should().ContainSingle(e => e.Path == $"{Root}/generated-docs/openapi.yaml");
        Module(snapshot, Root).Comparisons.Single(c => c.Family == "HTTP routes").State.Should().Be(GeneratedComparisonState.PotentiallyDrifted);
        var run = await Diagnostic(db).RunAsync(new GeneratedDocumentationDiagnosticRequest());
        run.Modules.Single(m => m.RootPath == Root).Status.Should().Be(GeneratedDocumentationHealthStatus.Warning, "semantic disagreement is never Fail");
    }

    [Fact]
    public async Task One_mismatch_stated_in_several_generated_documents_is_one_candidate_with_several_evidence_references()
    {
        using var db = Db();
        var files = Orders(documentedRoutes: ["/orders", "/invoices"], sourceRoutes: ["/orders"]);
        files[files.FindIndex(f => f.Path.EndsWith("architecture.md"))] = ($"{Root}/generated-docs/architecture.md", Architecture + "\nRoutes: `GET /invoices`.\n");
        var snapshot = await AnalyzeAsync(db, files);
        var drift = snapshot.GeneratedDocumentation!.Drift.Where(d => d.StructuredKey == "GET /invoices").ToList();
        drift.Should().ContainSingle();
        drift[0].LeftEvidence.Select(e => e.Path).Should().BeEquivalentTo([$"{Root}/generated-docs/openapi.yaml", $"{Root}/generated-docs/architecture.md"]);
    }

    [Fact]
    public async Task Generated_contract_drift_against_a_source_schema_in_the_same_module()
    {
        using var db = Db();
        var files = Orders();
        files.Add(($"{Root}/generated-docs/schema.graphql", "# Last updated: 2026-03-01\ntype Query { orders: [Order!]! }\ntype Order { id: ID! total: Float! }\n"));
        files.Add(($"{Root}/src/Shop.Orders.Api/Schema/schema.graphql", "type Query { orders: [Order!]! }\ntype Order { id: ID! total: Decimal! }\n"));
        var snapshot = await AnalyzeAsync(db, files);
        Module(snapshot, Root).Comparisons.Single(c => c.Family == "GraphQL schema").State.Should().Be(GeneratedComparisonState.PotentiallyDrifted);
        snapshot.GeneratedDocumentation!.Drift.Should().Contain(d => d.Family == "GraphQL schema" && d.DifferenceKind == DriftDifferenceKind.ValueMismatch && d.StructuredKey.Contains("Order.total"));
    }

    [Fact]
    public async Task A_generated_contract_that_does_not_parse_is_the_only_failure()
    {
        using var db = Db();
        var files = Orders(workflow: false).Where(f => !f.Path.EndsWith("openapi.yaml")).ToList();
        files.Add(($"{Root}/generated-docs/openapi.json", "{ \"openapi\": \"3.0.1\", \"paths\": { \"/orders\": { "));
        var snapshot = await AnalyzeAsync(db, files);
        Doc(snapshot, $"{Root}/generated-docs/openapi.json").StructurallyInvalid.Should().BeTrue();
        var run = await Diagnostic(db).RunAsync(new GeneratedDocumentationDiagnosticRequest());
        run.Modules.Single(m => m.RootPath == Root).Status.Should().Be(GeneratedDocumentationHealthStatus.Fail);
        run.Summary.StructuralFailures.Should().Be(1);
    }

    [Fact]
    public async Task Generated_markdown_is_fingerprinted_over_its_full_content_without_truncation()
    {
        using var db = Db();
        var longDoc = "Last updated: 2026-03-01\n\n# Architecture\n\n" + string.Join("\n", Enumerable.Range(1, 6000).Select(i => $"Line {i} of the generated architecture description."));
        var files = Orders();
        files[files.FindIndex(f => f.Path.EndsWith("architecture.md"))] = ($"{Root}/generated-docs/architecture.md", longDoc);
        var snapshot = await AnalyzeAsync(db, files);
        var doc = Doc(snapshot, $"{Root}/generated-docs/architecture.md");
        doc.Lines.Should().Be(longDoc.Split('\n').Length);
        doc.Bytes.Should().Be(Encoding.UTF8.GetByteCount(longDoc));
        doc.ContentFingerprint.Should().Be(Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(longDoc))).ToLowerInvariant());
    }

    // ── Authored vs generated ──

    [Fact]
    public async Task Specification_routes_that_match_give_no_drift_and_a_mismatch_is_a_specification_drift()
    {
        using var db = Db();
        var snapshot = await AnalyzeAsync(db, Orders(), importId: "import-a");
        var spec = Authored("Specification", $"{Root}/specs/001-orders/spec.md", "# Spec\n\n- **FR-001**: GET /orders lists orders.\n- **FR-002**: GET /refunds lists refunds.\n");
        var run = await Diagnostic(db).RunAsync(new GeneratedDocumentationDiagnosticRequest { ProjectImportId = "import-a", AuthoredArtifacts = [spec] });
        run.Authored.Compared.Should().BeTrue();
        var drift = run.Drift.Where(d => d.DriftType == CrossArtifactDriftType.SpecificationDrift).ToList();
        drift.Should().ContainSingle(d => d.StructuredKey == "GET /refunds");
        drift.Should().NotContain(d => d.StructuredKey == "GET /orders");
        drift[0].LeftEvidence[0].Kind.Should().Be("Specification");
        drift[0].ArtifactFingerprint.Should().Be(spec.Fingerprint);
        drift[0].WhyReview.Should().Contain("does not supersede the specification");
    }

    [Fact]
    public async Task Source_and_generated_are_both_referenced_and_neither_overwrites_the_other()
    {
        using var db = Db();
        var snapshot = await AnalyzeAsync(db, Orders(documentedRoutes: ["/orders"], sourceRoutes: ["/orders", "/payments"]), importId: "import-a");
        var spec = Authored("Specification", $"{Root}/specs/001-orders/spec.md", "# Spec\n\nGET /payments returns payments.\n");
        var run = await Diagnostic(db).RunAsync(new GeneratedDocumentationDiagnosticRequest { ProjectImportId = "import-a", AuthoredArtifacts = [spec] });
        var drift = run.Drift.Single(d => d.DriftType == CrossArtifactDriftType.SpecificationDrift && d.StructuredKey == "GET /payments");
        drift.RightEvidence.Should().Contain(e => e.Kind == "Generated documentation");
        drift.RightEvidence.Should().Contain(e => e.Kind == "Source evidence" && e.Value == "present");
        drift.Explanation.Should().Contain("Source declares it");
        // The generated evidence of the snapshot is unchanged by the comparison.
        Module(snapshot, Root).SourceKeys.Routes.Should().Contain("GET /payments");
        Doc(snapshot, $"{Root}/generated-docs/openapi.yaml").Keys.Routes.Should().Equal("GET /orders");
    }

    [Fact]
    public async Task Specification_contract_vs_generated_contract_reports_specified_intent_without_superseding_it()
    {
        using var db = Db();
        var files = Orders();
        files.Add(($"{Root}/specs/001-orders/contracts/orders-api.yaml", OpenApi("/orders", "/orders/{id}").Replace("x-last-updated", "x-spec")));
        var snapshot = await AnalyzeAsync(db, files);
        var drift = snapshot.GeneratedDocumentation!.Drift.Where(d => d.DriftType == CrossArtifactDriftType.SpecificationDrift).ToList();
        drift.Should().ContainSingle(d => d.StructuredKey.Contains("GET /orders/{id}") && d.DifferenceKind == DriftDifferenceKind.MissingOnRight);
        drift[0].LeftEvidence[0].Kind.Should().Be("Specification contract");
        drift[0].WhyReview.Should().Contain("does not supersede");
    }

    [Fact]
    public async Task Constitution_drift_needs_an_explicit_rule_that_governs_the_technology()
    {
        using var db = Db();
        var files = Orders();
        files[files.FindIndex(f => f.Path.EndsWith("architecture.md"))] = ($"{Root}/generated-docs/architecture.md", Architecture + "\nRead models are cached in MongoDB.\n");
        var snapshot = await AnalyzeAsync(db, files, importId: "import-a");
        var constitution = Authored("Constitution", $"{Root}/.specify/memory/constitution.md",
            "# Constitution\n\nServices MUST NOT use MongoDB.\nEvents published to Kafka MUST NOT contain personal data.\n");
        var run = await Diagnostic(db).RunAsync(new GeneratedDocumentationDiagnosticRequest { ProjectImportId = "import-a", AuthoredArtifacts = [constitution] });
        var drift = run.Drift.Where(d => d.DriftType == CrossArtifactDriftType.ConstitutionDrift).ToList();
        drift.Should().ContainSingle();
        drift[0].StructuredKey.Should().Be("Prohibited: MongoDB");
        drift[0].LeftEvidence[0].Line.Should().Be(3);
    }

    [Fact]
    public async Task Plan_drift_from_a_structured_technical_context_field()
    {
        using var db = Db();
        var snapshot = await AnalyzeAsync(db, Orders(), importId: "import-a");
        var plan = Authored("Plan", $"{Root}/specs/001-orders/plan.md", "# Plan\n\n## Technical Context\n\n**Language/Version**: C# 12\n**Storage**: PostgreSQL\n");
        var run = await Diagnostic(db).RunAsync(new GeneratedDocumentationDiagnosticRequest { ProjectImportId = "import-a", AuthoredArtifacts = [plan] });
        var drift = run.Drift.Single(d => d.DriftType == CrossArtifactDriftType.PlanDrift);
        drift.DifferenceKind.Should().Be(DriftDifferenceKind.ValueMismatch);
        drift.Explanation.Should().Contain("PostgreSQL").And.Contain("SQL Server");
    }

    [Fact]
    public async Task A_completed_task_supported_only_by_generated_documentation_is_not_independently_verified()
    {
        using var db = Db();
        var snapshot = await AnalyzeAsync(db, Orders(documentedRoutes: ["/orders", "/invoices"], sourceRoutes: ["/orders"]), importId: "import-a");
        var tasks = Authored("Tasks", $"{Root}/specs/001-orders/tasks.md", "# Tasks\n\n- [X] T010 Implement GET /invoices endpoint\n- [ ] T011 Document GET /invoices\n- [X] T012 Implement GET /orders\n");
        var run = await Diagnostic(db).RunAsync(new GeneratedDocumentationDiagnosticRequest { ProjectImportId = "import-a", AuthoredArtifacts = [tasks] });
        var delivery = run.Drift.Where(d => d.DriftType == CrossArtifactDriftType.DeliveryDrift).ToList();
        delivery.Should().ContainSingle(d => d.StructuredKey == "T010: GET /invoices");
        delivery[0].Explanation.Should().StartWith("Task completion not independently verified");
        delivery[0].Explanation.Should().NotContain("incomplete");
        delivery[0].RelatedFindings.Should().Contain(r => r.Contains("Implementation Review"));
    }

    // ── Snapshot binding and project isolation ──

    [Fact]
    public async Task A_historical_snapshot_is_evaluated_with_its_own_evidence_only()
    {
        using var db = Db();
        var current = await AnalyzeAsync(db, Orders());
        var historical = current with { Id = Guid.NewGuid(), AnalyzedAt = current.AnalyzedAt.AddDays(-30), GeneratedDocumentation = null };
        db.IqrSourceSnapshots.Add(new IqrSourceSnapshotRecord { Id = historical.Id, EnvironmentId = IqrSourceStore.NoEnvironment, IntegrationId = IqrSourceStore.SourceAnalysisOwner,
            AnalyzedAt = historical.AnalyzedAt, EvidenceJson = JsonSerializer.Serialize(historical, new JsonSerializerOptions(JsonSerializerDefaults.Web)) });
        await db.SaveChangesAsync();
        var run = await Diagnostic(db).RunAsync(new GeneratedDocumentationDiagnosticRequest { SnapshotId = historical.Id });
        run.State.Should().Be(GeneratedDocumentationRunState.NotAvailableForSnapshot);
        run.Snapshot!.SnapshotId.Should().Be(historical.Id);
        run.Modules.Should().BeEmpty("the newer snapshot's evidence is never substituted");
        var newest = await Diagnostic(db).RunAsync(new GeneratedDocumentationDiagnosticRequest());
        newest.Snapshot!.SnapshotId.Should().Be(current.Id);
        newest.Snapshot.IsNewest.Should().BeTrue();
    }

    [Fact]
    public async Task Project_isolation_never_mixes_another_projects_snapshot_or_artifacts()
    {
        using var db = Db();
        var projectA = await AnalyzeAsync(db, Orders(), importId: "import-a");
        var projectB = await AnalyzeAsync(db, Orders(documentedRoutes: ["/orders", "/invoices"]), importId: "import-b");
        var spec = Authored("Specification", $"{Root}/specs/001-orders/spec.md", "# Spec\n\nGET /refunds\n");
        var runA = await Diagnostic(db).RunAsync(new GeneratedDocumentationDiagnosticRequest { ProjectImportId = "import-a", AuthoredArtifacts = [spec] });
        runA.Snapshot!.SnapshotId.Should().Be(projectA.Id);
        runA.Drift.Should().NotContain(d => d.StructuredKey == "GET /invoices", "project B's documentation drift is not project A's");
        var crossRequest = await Diagnostic(db).RunAsync(new GeneratedDocumentationDiagnosticRequest { SnapshotId = projectB.Id, ProjectImportId = "import-a", AuthoredArtifacts = [spec] });
        crossRequest.State.Should().Be(GeneratedDocumentationRunState.NoSnapshot);
        crossRequest.Modules.Should().BeEmpty();
        var noSnapshot = await Diagnostic(db).RunAsync(new GeneratedDocumentationDiagnosticRequest { ProjectImportId = "import-c", AuthoredArtifacts = [spec] });
        noSnapshot.State.Should().Be(GeneratedDocumentationRunState.NoSnapshot);
        // A workspace that is not the snapshot's imported project gets no authored comparison.
        var unbound = await Diagnostic(db).RunAsync(new GeneratedDocumentationDiagnosticRequest { SnapshotId = projectA.Id, AuthoredArtifacts = [spec] });
        unbound.Authored.Compared.Should().BeFalse();
        unbound.Drift.Should().NotContain(d => d.DriftType == CrossArtifactDriftType.SpecificationDrift && d.StructuredKey == "GET /refunds");
    }

    [Fact]
    public async Task Results_are_cached_by_snapshot_evidence_and_authored_fingerprints()
    {
        using var db = Db();
        await AnalyzeAsync(db, Orders(), importId: "import-a");
        var service = Diagnostic(db);
        var spec = Authored("Specification", $"{Root}/specs/001-orders/spec.md", "# Spec\n\nGET /refunds\n");
        var first = await service.RunAsync(new GeneratedDocumentationDiagnosticRequest { ProjectImportId = "import-a", AuthoredArtifacts = [spec] });
        var second = await service.RunAsync(new GeneratedDocumentationDiagnosticRequest { ProjectImportId = "import-a", AuthoredArtifacts = [spec] });
        first.FromCache.Should().BeFalse();
        second.FromCache.Should().BeTrue();
        var changed = Authored("Specification", $"{Root}/specs/001-orders/spec.md", "# Spec\n\nGET /refunds\nGET /returns\n");
        (await service.RunAsync(new GeneratedDocumentationDiagnosticRequest { ProjectImportId = "import-a", AuthoredArtifacts = [changed] })).FromCache.Should().BeFalse();
    }

    [Fact]
    public async Task No_generated_documentation_gives_the_neutral_empty_state()
    {
        using var db = Db();
        await AnalyzeAsync(db, Orders().Where(f => !f.Path.Contains("generated-docs")).ToList());
        var run = await Diagnostic(db).RunAsync(new GeneratedDocumentationDiagnosticRequest());
        run.State.Should().Be(GeneratedDocumentationRunState.NoGeneratedDocumentation);
        run.StateMessage.Should().Be(GeneratedDocumentationText.EmptyState);
        run.Modules.Should().BeEmpty();
    }

    [Fact]
    public void Source_route_attributes_are_read_with_controller_prefixes()
    {
        var routes = SourceRouteReader.AttributeRoutes("""
            [ApiController]
            [Route("api/[controller]")]
            public sealed class OrdersController : ControllerBase
            {
                [HttpGet("{id:guid}")] public IActionResult Get(Guid id) => Ok();
                [HttpPost] public IActionResult Create() => Ok();
            }
            public static class Endpoints { [WolverineGet("/health/ping")] public static string Ping() => "ok"; }
            """).ToList();
        routes.Should().BeEquivalentTo(["GET /api/orders/{}", "POST /api/orders", "GET /health/ping"]);
        StructuredKeys.SameRoute("GET /api/v1/orders/{}", "GET /orders/{}").Should().BeTrue("a route group prefix may be outside the evidence");
        StructuredKeys.SameRoute("GET /orders", "POST /orders").Should().BeFalse();
    }

    private static GeneratedDocumentationDiagnosticService Diagnostic(BirkNext.Api.Data.AppDbContext db) => new(new IqrSourceStore(db), new MemoryCache(new MemoryCacheOptions()));
}
