using BirkNext.DatabaseArchitecture;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BirkNext.Api.Services.DatabaseArchitecture;

/// <summary>Migration declarations are a separate source layer, never deployed schema.</summary>
public sealed class MigrationSchemaExtractor : IDatabaseSchemaExtractor
{
    public string Name => "EF migration syntax";
    public string Version => "2";
    public bool CanAnalyze(DatabaseExtractionInput input) => input.Workspace.Files.Any(f => f.Content.Contains("Migration"));
    public Task<DatabaseExtractionResult> AnalyzeAsync(DatabaseExtractionInput input, CancellationToken cancellationToken)
    {
        var databases = new List<DatabaseModel>(); var unresolved = new List<DatabaseEvidence>(); var diagnostics = new List<string>();
        foreach (var file in input.Workspace.Files.Where(f => f.Path.EndsWith(".cs") && !f.Path.EndsWith(".Designer.cs") && f.Content.Contains("migrationBuilder.")).OrderBy(f => f.Path, StringComparer.Ordinal))
        {
            cancellationToken.ThrowIfCancellationRequested();
            var root = CSharpSyntaxTree.ParseText(file.Content, cancellationToken: cancellationToken).GetRoot();
            foreach (var migration in root.DescendantNodes().OfType<ClassDeclarationSyntax>().Where(c => c.BaseList?.Types.Any(t => t.Type.ToString().Split('.').Last() == "Migration") == true))
            {
                var project = Extraction.Project(input, file.Path);
                var designer = input.Workspace.Files.FirstOrDefault(f => f.Path == file.Path[..^3] + ".Designer.cs");
                var metadataRoot = designer is null ? root : CSharpSyntaxTree.ParseText(designer.Content, cancellationToken: cancellationToken).GetRoot();
                var contextAttribute = metadataRoot.DescendantNodes().OfType<AttributeSyntax>().FirstOrDefault(a => a.Name.ToString().Split('.').Last() is "DbContext" or "DbContextAttribute");
                var contextType = contextAttribute?.ArgumentList?.Arguments.FirstOrDefault()?.Expression as TypeOfExpressionSyntax;
                var contextName = contextType is null ? null : Extraction.Safe(contextType.Type.ToString().Split('.').Last());
                var db = databases.FirstOrDefault(d => d.SourceProject == Extraction.Safe(project) && d.DbContext == contextName);
                if (db is null) { db = new DatabaseModel { Id = Extraction.Id(project + ":migrations:" + contextName), LogicalName = "Migration database candidate", DbContext = contextName, SourceProject = Extraction.Safe(project) }; databases.Add(db); }
                if (contextAttribute is not null) Extraction.Add(db, Extraction.Evidence(input, designer?.Path ?? file.Path, contextAttribute, Name, "Migration DbContext ownership metadata", DatabaseEvidenceState.ObservedFromMigration));
                var origin = file.Content.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase) ? "Generated migration " : "Migration (generation unknown) ";
                var up = migration.Members.OfType<MethodDeclarationSyntax>().FirstOrDefault(m => m.Identifier.ValueText == "Up"); if (up is null) continue;
                foreach (var call in up.DescendantNodes().OfType<InvocationExpressionSyntax>())
                {
                    var method = Extraction.Method(call);
                    if (call.Expression is not MemberAccessExpressionSyntax { Expression: IdentifierNameSyntax receiver } || receiver.Identifier.ValueText != "migrationBuilder") continue;
                    var ev = Extraction.Evidence(input, file.Path, call, Name, origin + method, DatabaseEvidenceState.ObservedFromMigration);
                    Extraction.Add(db, ev);
                    var name = Extraction.Literal(Extraction.Arg(call, method is "AddColumn" or "AlterColumn" or "DropColumn" or "RenameColumn" or "AddForeignKey" or "DropForeignKey" or "CreateIndex" or "DropIndex" or "AddPrimaryKey" or "DropPrimaryKey" ? "table" : "name"));
                    var schema = Extraction.Literal(Extraction.Arg(call, "schema"));
                    if (name is null) { unresolved.Add(ev with { State = DatabaseEvidenceState.Unresolved, Explanation = "Migration object identity not literal" }); continue; }
                    var table = Extraction.Table(db, name, schema, ev);
                    if (method == "DropTable") { foreach (var s in db.Schemas) s.Tables.Remove(table); continue; }
                    if (method == "CreateTable")
                    {
                        var columns = Extraction.Arg(call, "columns");
                        foreach (var member in columns?.DescendantNodes().OfType<AnonymousObjectMemberDeclaratorSyntax>() ?? [])
                        {
                            var columnCall = member.Expression.DescendantNodesAndSelf().OfType<InvocationExpressionSyntax>().FirstOrDefault(i => Extraction.Method(i) == "Column");
                            if (columnCall is null) continue;
                            var cn = Extraction.Literal(Extraction.Arg(columnCall, "name")) ?? member.NameEquals?.Name.Identifier.ValueText;
                            if (cn is null) continue;
                            var column = Extraction.Column(table, Extraction.Safe(cn), Extraction.Evidence(input, file.Path, member, Name, origin + "Column", DatabaseEvidenceState.ObservedFromMigration));
                            column.StoreType = Extraction.SqlType(Extraction.Arg(columnCall, "type")); column.Nullable = Extraction.Bool(Extraction.Arg(columnCall, "nullable"));
                            Extraction.Assert(column, "StoreType", column.StoreType, ev); Extraction.Assert(column, "Nullable", column.Nullable, ev);
                            column.MaxLength = Extraction.Number(Extraction.Arg(columnCall, "maxLength")); column.Precision = Extraction.Number(Extraction.Arg(columnCall, "precision")); column.Scale = Extraction.Number(Extraction.Arg(columnCall, "scale"));
                            if (columnCall.Expression is MemberAccessExpressionSyntax { Name: GenericNameSyntax g }) column.ClrType = Extraction.Safe(g.TypeArgumentList.Arguments.First().ToString());
                        }
                        foreach (var constraint in Extraction.Arg(call, "constraints")?.DescendantNodes().OfType<InvocationExpressionSyntax>() ?? [])
                        {
                            var ce = Extraction.Evidence(input, file.Path, constraint, Name, origin + Extraction.Method(constraint), DatabaseEvidenceState.ObservedFromMigration);
                            if (Extraction.Method(constraint) == "PrimaryKey") Extraction.Key(table, Extraction.Columns(Extraction.Arg(constraint, "columns", 1)), ce);
                            if (Extraction.Method(constraint) == "ForeignKey") AddForeignKey(table, constraint, ce);
                            if (Extraction.Method(constraint) == "UniqueConstraint") { var unique = new ConstraintModel { Name = Extraction.Literal(Extraction.Arg(constraint, "name", 0)), Type = "Unique", Columns = Extraction.Columns(Extraction.Arg(constraint, "columns", 1)) }; Extraction.Add(unique, ce); table.Constraints.Add(unique); }
                        }
                    }
                    else if (method is "AddColumn" or "AlterColumn")
                    {
                        var cn = Extraction.Literal(Extraction.Arg(call, "name")); if (cn is null) { unresolved.Add(ev); continue; }
                        var column = Extraction.Column(table, cn, ev); column.StoreType = Extraction.SqlType(Extraction.Arg(call, "type")); column.Nullable = Extraction.Bool(Extraction.Arg(call, "nullable"));
                        // Only the final declaration in this migration stream is compared to the model; prior operations remain evidence.
                        column.Assertions.RemoveAll(a => a.Fact is "StoreType" or "Nullable");
                        Extraction.Assert(column, "StoreType", column.StoreType, ev); Extraction.Assert(column, "Nullable", column.Nullable, ev);
                    }
                    else if (method == "DropColumn") table.Columns.RemoveAll(c => c.Name == Extraction.Literal(Extraction.Arg(call, "name")));
                    else if (method == "RenameColumn") { var column = table.Columns.FirstOrDefault(c => c.Name == Extraction.Literal(Extraction.Arg(call, "name"))); if (column is not null) column.Name = Extraction.Literal(Extraction.Arg(call, "newName")) ?? column.Name; }
                    else if (method == "RenameTable") { table.PhysicalName = Extraction.Literal(Extraction.Arg(call, "newName")) ?? table.PhysicalName; table.LogicalName = table.PhysicalName!; table.SchemaName = Extraction.Literal(Extraction.Arg(call, "newSchema")) ?? table.SchemaName; }
                    else if (method == "AddPrimaryKey") Extraction.Key(table, Extraction.Columns(Extraction.Arg(call, "columns") ?? Extraction.Arg(call, "column")), ev);
                    else if (method == "DropPrimaryKey") { table.PrimaryKey = null; foreach (var c in table.Columns) c.IsPrimaryKey = false; }
                    else if (method == "AddForeignKey") AddForeignKey(table, call, ev);
                    else if (method == "DropForeignKey") { var fkName = Extraction.Literal(Extraction.Arg(call, "name")); table.ForeignKeys.RemoveAll(f => f.Name == fkName); table.Relationships.RemoveAll(f => f.Name == fkName); }
                    else if (method == "CreateIndex") { var ix = new IndexModel { Name = Extraction.Literal(Extraction.Arg(call, "name")), Columns = Extraction.Columns(Extraction.Arg(call, "columns") ?? Extraction.Arg(call, "column")), Unique = Extraction.Bool(Extraction.Arg(call, "unique")) ?? false }; Extraction.Add(ix, ev); table.Indexes.Add(ix); }
                    else if (method == "DropIndex") table.Indexes.RemoveAll(i => i.Name == Extraction.Literal(Extraction.Arg(call, "name")));
                    else { unresolved.Add(ev with { State = DatabaseEvidenceState.Unresolved, Explanation = method + " not replayed; migration declaration retained" }); }
                }
            }
        }
        if (databases.Count == 0) diagnostics.Add("No supported EF migration operations found.");
        foreach (var schemaFile in input.Workspace.Files.Where(f => f.Path.EndsWith("ModelSnapshot.cs"))) diagnostics.Add("Model snapshot source retained in archive inventory; BuildModel assertions are not interpreted in v1: " + Extraction.Safe(schemaFile.Path));
        diagnostics.Add("Migration operations are ordered by source path, not deployment history; branching and custom SQL require review.");
        return Task.FromResult(new DatabaseExtractionResult(databases, unresolved, diagnostics));
    }
    private static void AddForeignKey(TableModel table, InvocationExpressionSyntax call, DatabaseEvidence ev)
    {
        var target = Extraction.Literal(Extraction.Arg(call, "principalTable")); if (target is null) return;
        Extraction.Relationship(table, target, Extraction.Columns(Extraction.Arg(call, "columns") ?? Extraction.Arg(call, "column")), Extraction.Columns(Extraction.Arg(call, "principalColumns") ?? Extraction.Arg(call, "principalColumn")), ev, "N:1", Extraction.Arg(call, "onDelete") is MemberAccessExpressionSyntax m ? m.Name.Identifier.ValueText : null);
        if (table.ForeignKeys.LastOrDefault() is { } relationship) { relationship.Name = Extraction.Literal(Extraction.Arg(call, "name", 0)); relationship.ToSchema = Extraction.Literal(Extraction.Arg(call, "principalSchema")); }
    }
}
